Dockerfile

This just creates a simple executable Docker image that runs the `uninitialized.sol` example by default.
Once merged, I'll set autobuilds up on Docker Hub.

Dockerfile: Add initial Dockerfile

---

README.md
scripts/travis_test.sh
slither/__main__.py
slither/detectors/naming_convention/naming_convention.py
tests/naming_convention.sol

This pr adds a detector for naming convention violations.
fixes #24
Some tests violate naming conventions  and I had to update the expected number of results in order for the tests to succeed.
I think it is better to limit each test case to only run the detector for which the test was made for.

Naming Convention Detector

---

slither/core/cfg/node.py
slither/core/declarations/function.py
slither/slithir/convert.py
slither/solc_parsing/cfg/node.py
slither/solc_parsing/declarations/function.py

This PR uses slihtIR to improve the following attributes of  `node` and `function`:
- `variables_read`
- `variables_written`
- `state_variables_read`
- `state_variables_written`
- `internal_call`
It replaces the attribute `external_calls` by:
- `solidity_calls`: returns the list of `SolidiyFunction` called
- `high_level_calls`: returns the list of `(Contract, Function|Variable)` called (it includes library calls). `Variable` is used for calls to public state variables.
- `low_level_calls`: returns the list of low level calls, represented by `(Variable|SolidityVariable, function_name)`, where `function_name` can be `call/delegatecall/codecall`
The PR should simplify the detectors and will be directly useful for https://github.com/trailofbits/slither/pull/49 and …

API changes

---

README.md
scripts/travis_test.sh
slither/__main__.py

- help is printed when no arguments are supplied
- rework detector arguments: detectors are now a comma-separated list, defaults to all
- rework printer arguments: printers are now a comma-separated list, defaults to contract-summary
- add version command
fixes #50

WIP: cli improvements

---

slither/detectors/attributes/old_solc.py
slither/detectors/functions/arbitrary_send.py

The descriptions for `solc-version` and `arbitrary-send` detectors were changed in the README but not in the actual detector code, this has been fixed.

update detector descriptions witht txt from README

---

slither/detectors/functions/arbitrary_send.py
slither/detectors/functions/complex_function.py
slither/detectors/functions/external_function.py
slither/detectors/functions/suicidal.py
slither/detectors/operations/low_level_calls.py
slither/detectors/reentrancy/reentrancy.py
slither/detectors/shadowing/shadowing_functions.py
slither/detectors/statements/assembly.py
slither/detectors/statements/tx_origin.py
tests/expected_json/arbitrary_send.arbitrary-send.json
tests/expected_json/backdoor.suicidal.json
tests/expected_json/external_function.external-function.json
tests/expected_json/inline_assembly_contract.assembly.json
tests/expected_json/inline_assembly_library.assembly.json
tests/expected_json/low_level_calls.low-level-calls.json
tests/expected_json/reentrancy.reentrancy.json
tests/expected_json/tx_origin.tx-origin.json

json output of the different detectors return different property name for the name of the function in which something was detected: `func`, `function`, `function_name`, and `funcs`, `functions`.
they all use the same property name: `function` and `functions`.

Normalize detectors json output function properties

---

Dockerfile

Verify that the solc binary is the one **we used** and noone changed it in the meantime.

Verify solc binary

---

slither/__main__.py

Adds support to be able to run `truffle compile` without having to install it globally.
Closes #105 
Truffle being used by default:
```
matt@delleite:contracts/ (master*) $ slither .                                                                                                                [18:11:18]
INFO:Slither:truffle compile running...
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
File "/usr/lib/python3.7/site-packages/slither_analyzer-0.3.1-py3.7.egg/slither/__main__.py", line 229, in main_impl
(results, number_contracts) = process_truffle(filename, args, detector_classes, printer_classes)
File "/usr/lib/python3.7/site-packages/slither_analyzer-0.3.1-py3.7.egg/slither/__main__.py", line 64, in process_truffle
process = subprocess.Popen(cmd, …
```

Add support for executing truffle locally

---

slither/core/variables/event_variable.py
slither/solc_parsing/variables/event_variable.py

This pull request aims to provide access to the 'indexed' attribute on event parameters, such that detectors can know if certain event parameters are indexed in the bloom filter. 
Indexed event parameters are included in a transaction's bloom filter in order for external tools to quickly look for transactions which contained that data (a specific receiving address, etc). This is especially important when considering that many tools expect events in the ERC20 specification to index certain parameters, and will miss an event log's inclusion in a set if the bloom filter returns a "not-indexed" result.
Exposing this attribute may be useful to detectors which check contracts that implement ERC specifications are well formed.

Expose "indexed" attribute on event parameters

---

scripts/json_diff.py
slither/__main__.py
slither/core/declarations/contract.py
slither/core/declarations/function.py
slither/core/solidity_types/array_type.py
slither/printers/call/call_graph.py
slither/printers/inheritance/inheritance_graph.py
slither/slither.py
slither/slithir/convert.py
slither/slithir/operations/internal_dynamic_call.py
slither/solc_parsing/declarations/contract.py
slither/solc_parsing/declarations/function.py
slither/solc_parsing/declarations/modifier.py
slither/solc_parsing/expressions/expression_parsing.py
slither/solc_parsing/slitherSolc.py
slither/visitors/slithir/expression_to_slithir.py

This pull request aims to resolve #131 . It aims to provide the immediate base contracts of a given contract in the correct order of declaration via `contract.immediate_inheritance`. This contrasts to the existing provided `contract.inheritance` which provides a flattened, linearized base contract list (all ancestors in the inheritance chain, immediate and not).

[WIP] Expose immediate base contracts and base constructors

---

slither/solc_parsing/declarations/function.py

This pull request aims to resolve #145 . It adds logic which improves the detection of missing for-loop components via information found in the `attributes` node.
Note: It seems some existing logic might have been trying to access this `attributes` data, but checked one node level higher (the parent of `attributes`, aka the for-loop node itself). Though the logic has been duplicated to maintain existing code, and additionally check `attributes`, in case this was done on purpose for older versions of solidity which may have changed the format.

Fix missing loop components on legacy-ast

---

slither/solc_parsing/solidity_types/type_parsing.py

This pull request resolves #160 and resolves #137 . It changes parsing on legacy-ast to use the `type` attribute instead of the `name` attribute, which provides more information, and was likely to be intended to be used from the start.
All relevant changes are in `type_parsing.py`. Please refer to the examples in both mentioned issues for examples of breaking behavior that has been fixed. 
A pass was done on over a thousand contracts to verify integrity of parsing. Further tests are always welcome, as this is a critical change.

Fix UserDefinedTypeName type parsing from names

---

slither/__main__.py

This pull request aims to resolve #173 . The `truffle compile` command invoked through slither will fail on Windows due to naming conflicts. On Windows, `.JS` is an executable extension by default (see the `PATHEXT` environment variable), which confuses windows into invoking `truffle.js` instead of `truffle.cmd`. 
Truffle's own website suggests a few fixes:
https://truffleframework.com/docs/truffle/reference/configuration#resolving-naming-conflicts-on-windows
The only fix which does not require the user modifying their environment is to explicitly invoke `truffle.cmd`. This seems simplistic and non-problematic, so I have added a switch to `__main__.py` which invokes `truffle.cmd` if on Windows, otherwise simply `truffle` is invoked.
This has fixed truffle invocation on my Windows system.

Fix Truffle invocation conflict on Windows

---

slither/analyses/data_dependency/data_dependency.py

Made inclusion of `GENERIC_TAINT` sources (`msg.*, tx.origin`) optional in taint-checking by adding `ignore_generic_taint` parameter to `is_tainted()` and `is_tainted_ssa()` functions, with the default value being `FALSE`.
Motivation: There are analyses where one would like to ignore these generic taint sources but only include taint coming from other user-controlled function arguments.
Validation: `tests/controlled_delegatecall.sol` passes with two violations as expected. `scripts/travis_test_data_dependency.sh` passes.

Made inclusion of GENERIC_TAINT sources (msg.*, tx.origin) optional in taint-checking

---

slither/detectors/attributes/const_functions.py
slither/detectors/attributes/incorrect_solc.py
slither/detectors/attributes/locked_ether.py
slither/detectors/erc20/incorrect_interface.py
slither/detectors/erc20/unindexed_event_parameters.py
slither/detectors/functions/suicidal.py
slither/detectors/operations/block_timestamp.py
slither/detectors/operations/unused_return_values.py
slither/detectors/statements/calls_in_loop.py
slither/detectors/statements/controlled_delegatecall.py
slither/detectors/statements/deprecated_calls.py
slither/detectors/statements/incorrect_strict_equality.py
slither/detectors/statements/tx_origin.py
slither/detectors/variables/uninitialized_local_variables.py
slither/detectors/variables/uninitialized_storage_variables.py
tests/controlled_delegatecall.sol

(1) Fixed minor typos in comments of some detectors.
(2) Fixed a typo in controlled_delegatecall detector where *callcode* was specified as *codecall*. Added a function to tests/controlled_delegatecall.sol to verify the fix.

Fixed typos in comments and controlled_delegatecall detector

---

examples/scripts/data_dependency.sol
slither/analyses/data_dependency/data_dependency.py
slither/core/declarations/function.py

This PR addresses https://github.com/crytic/slither/issues/192 to fix data dependency to propagate return values of functions to call sites.
With this fix, for the below contract:
```
contract PropagateThroughReturnValue {
uint var_dependant;
uint var_state;
function foo() public {
var_dependant = bar();
}
function bar() internal returns (uint) {
return (var_state);
}
}
```
the `data_dependency` printer output below shows that `var_dependent` in `foo` depends on `var_state` returned from `bar` because of the call site `var_dependant = bar();` in `foo`:
```
Contract PropagateThroughReturnValue
+---------------+---------------+
|    Variable   |  Dependencies |
+---------------+---------------+
| var_dependant | ['var_state'] |
|   var_state   | ['var_state'] | …
```

 Fixed data dependency to propagate return values of functions to call sites

---

setup.py
slither/__main__.py
slither/core/source_mapping/source_mapping.py
slither/solc_parsing/slitherSolc.py

This issue aims to resolve #180 . By default, python's `open()` function parses CR LF (`\r\n`) line endings as LF (`\n`). During line number calculation, a byte offset is converted into line numbers by splitting the string with a `\n` character, and summing up the length of each line until the correct line byte range is found. With the removal of CR control characters, a miscalculation of line lengths would cause a later-than-intended line range to be reported.
This fixes the issue by adding a `newline=''` argument to the `open()` functions related to source mapping. The use of a blank new line will allow python's new line related parsing functions to work, while retaining CR LF line endings. Reference: https://stackoverflow.com/questions/20350305/python-read-crlf-text-file-as-is-with-crlf …

Bug fix for line number calculations

---

scripts/travis_test_4.sh
slither/detectors/all_detectors.py
slither/detectors/source/rtlo.py
tests/expected_json/right_to_left_override.rtlo.json
tests/right_to_left_override.sol

As can be seen in https://youtu.be/P_Mtd5Fc_3E?t=1813

Add right-to-left-override character (U+202E) detection

---

slither/printers/summary/function_ids.py

This pull request aims to resolve #210 . The `function-id` printer will now consider that some public variable getter functions take input:
- Getters for `mapping` types take a key as input.
- Getters for array types take a `uint256` index as input.
The printer will now generate the correct function identifiers.

Fix functionid printer to account for some getters taking input

---

slither/core/declarations/function.py
slither/core/declarations/structure.py
slither/core/expressions/literal.py
slither/core/solidity_types/array_type.py
slither/core/variables/state_variable.py
slither/slithir/convert.py
slither/slithir/variables/constant.py
slither/solc_parsing/declarations/structure.py
slither/solc_parsing/expressions/expression_parsing.py
slither/solc_parsing/solidity_types/type_parsing.py
slither/utils/type.py
slither/visitors/expression/constants_folding.py
slither/visitors/slithir/expression_to_slithir.py

Close https://github.com/crytic/slither/issues/223
- Improve literals parsing and Constant conversion:
- add bool type to constant
- convert integer using 'e' (1e10)
- convert constant uint -> int when possible
- Api added:
- Constant.original_value: str version of the constant expression
- Structure.elems_ordered: keep original structure declaration order
https://github.com/crytic/slither/pull/216 will need to use `constant.original_value`

Improve conversion of Literals 

---

scripts/tests_generate_expected_json_5.sh
scripts/travis_test_5.sh
scripts/travis_test_etherscan.sh
slither/detectors/attributes/incorrect_solc.py
tests/expected_json/solc_version_incorrect_05.ast.json.solc-version.json
tests/expected_json/solc_version_incorrect_05.ast.json.solc-version.txt
tests/solc_version_incorrect_05.ast.json
tests/solc_version_incorrect_05.sol

Add two new types of incorrect Solidity: too new (>=5.4), and buggy versions (0.4.22, 0.5.5, 0.5.6).
Close #189

Improve solc-version detector

---

slither/core/declarations/solidity_variables.py
slither/core/solidity_types/__init__.py
slither/core/solidity_types/type_information.py
slither/slithir/convert.py

This PR adds support for `type(X)` operation: https://solidity.readthedocs.io/en/latest/units-and-global-variables.html#type-information

Add support for type(X) operation (creationCode, runtimeCode, name)

---

slither/core/cfg/node.py
slither/core/declarations/contract.py
slither/core/declarations/function.py
slither/solc_parsing/cfg/node.py
slither/solc_parsing/declarations/function.py
slither/solc_parsing/expressions/expression_parsing.py

This PR replaces PR #233 which was created against a stale `dev` branch by mistake. Same set of changes as PR #233 required for slither-format tool:
1. Adds _internal_calls_as_expressions to complement _external_calls_as_expressions
2. Adds source_mapping hooks for function parameters and returns
3. Sets source_mapping offsets for function calls, modifier calls and identifier uses

slither core/parsing changes required for slither-format

---

slither/core/declarations/contract.py
slither/printers/summary/variable_order.py
slither/solc_parsing/declarations/contract.py

- Keep track of the declaration order + shadowed variables
- Print canonical name in the variable order printer
Fix #250

API: add contract.state_variables_ordered

---

slither/core/source_mapping/source_mapping.py
tests/source_mapping.sol

This PR aims to resolve #251 . Source mapping was previously calculating based off of character/string length, as opposed to byte length. Source code is now encoded in utf-8 format prior to any length calculations.

[WIP] Fix source mapping where utf8 char length != byte length

---

slither/visitors/slithir/expression_to_slithir.py

I think another case where types are incorrect is in:
```
function addTest(uint8 a, uint32 b) external pure returns(uint32){
return a+b;
}
```
because the lvalue type is automatically set to `variable_left`  https://github.com/crytic/slither/blob/5d6ab217a84be5147c46476ad1ea18b000eef87b/slither/slithir/convert.py#L365
but this isn't always correct, because type of uint X+uint Y should be uint max(X,Y)   (same for int)

Fix types of inserted constants

---

slither/core/declarations/function.py

Should we also add a `fallback_function` parameter to Contract to retrieve the fallback function?

add is_fallback parameter to Function

---

slither/__main__.py
slither/core/slither_core.py
slither/core/source_mapping/source_mapping.py
slither/slither.py

This pull request aims to move all glob pattern matching and other compilation related code from slither into crytic-compile, and add support for crytic-compile exported archives (in accordance with https://github.com/crytic/crytic-compile/pull/24).
For more information, read the above referenced pull request.

Support for crytic-compile exported archives + simplified main entry point

---

slither/__main__.py
slither/utils/command_line.py

This PR fixes:
- the config file options that are not correctly sent to `crytic-compile`
- the legacy options in Slither that are not anymore relevant
See https://github.com/crytic/slither/issues/289

Fix config file 

---

scripts/tests_generate_expected_json_4.sh
scripts/tests_generate_expected_json_5.sh
scripts/travis_test_5.sh
slither/core/cfg/node.py
slither/core/declarations/function.py
slither/detectors/all_detectors.py
slither/detectors/operations/void_constructor.py
slither/printers/summary/slithir.py
slither/slithir/convert.py
slither/slithir/operations/__init__.py
slither/slithir/operations/nop.py
slither/solc_parsing/declarations/contract.py
slither/solc_parsing/declarations/function.py
slither/visitors/slithir/expression_to_slithir.py
tests/expected_json/void-cst.void-cst.json
tests/expected_json/void-cst.void-cst.txt
tests/void-cst.sol

- Add support for ternary operator in modifier/constructor calls (`function f() public modif( condition?1:2)`)
- Add NOP IR to represent void constructor
- Add void-constructor detector
Void constructors are calls to non-existing constructor, such as:
```
contract C{ }
contract D is C{
constructor() public C(){
}
}
```

Improvements on modifier/constructor calls support

---

slither/core/cfg/node.py
slither/core/children/child_node.py
slither/core/declarations/function.py
slither/detectors/reentrancy/reentrancy.py
slither/slithir/operations/call.py
slither/slithir/operations/high_level_call.py
slither/slithir/operations/library_call.py
slither/slithir/operations/low_level_call.py
slither/slithir/operations/new_contract.py
slither/utils/function.py

This PR cleans the reentrancy fix point module by moving part of the logic to the IR level. The reentrancy detector will be easier to read and maintain. Additionally, other modules can benefit from the re-enter and ethers sent information. 
Changes: 
- Create `can_renter` and `can_send_ether` functions for all the `Call` IRs. Additionally, these functions are accessible at the `node` and `function` level.
- Add support for create-based reentrancy (https://github.com/crytic/slither/issues/310)
This PR needs extra testing to ensure that the heuristics are correctly conserved.

Refactor reentrancy + API changes

---

examples/printers/constructors.sol
slither/printers/all_printers.py
slither/printers/summary/constructor_calls.py

Till now it gets an instance of constructors from all the contract following c3 linearization and prints internal call instead of the inline version of the constructor.
Also, I have a question, is there something pre-written to get the inline form of function (that i am not able to find) or do I have to write it?
Please point me in the right direction.
This pr is for issue #271

[WIP]Printer: constructor summary

---

slither/detectors/naming_convention/naming_convention.py

ignore naming convention restriction on echidna_ and crytic_ functions

---

slither/__main__.py

This way we can see:
```
INFO:Slither:. analyzed (X contracts with 38 detectors), Y result(s) found
```
for public Slither version and more for the private one ;).

Print detectors count on Slither CLI

---

README.md

Banged my head against the wall for hours trying to install older versions of solc to test Slither. Turns out, I could've skipped all that by just using [solc-select](https://github.com/crytic/solc-select). It's an amazing tool. It just works. I love it. Added a few sentences to the README to recommend using solc-select for older contracts.

Added solc-select to installation section of README.md

---

slither/solc_parsing/declarations/function.py

Example:
```solidity
contract C{
for(;;){
if(true){
break;
}
}
return;
}
}
```

Fix parsing of infinite loop with break

---

slither/slithir/convert.py
slither/solc_parsing/declarations/function.py

An incorrect order in the conversion operation was preventing abi.decode to be properly translated
Example
```solidity
pragma experimental ABIEncoderV2;
interface Data{
struct St{
uint a;
uint b;
}
}
library Lib{
}
contract C is Data{
using Lib for address;
function g(bytes memory to_decode) public{
St[] memory s = abi.decode(to_decode, (St[]));
return ;
}
}
```

Fix incorrect abi.decode translation

---

slither/detectors/variables/unused_state_variables.py

#333 lead to miss some results

Fix unused state

---

scripts/travis_test_dapp.sh

Similar to https://github.com/crytic/crytic-compile/pull/42

Use cache to speed up dapp travis test

---

scripts/travis_test_dapp.sh
scripts/travis_test_etherscan.sh
slither/detectors/functions/external_function.py
tests/expected_json/external_function.external-function.json
tests/expected_json/external_function.external-function.txt
tests/expected_json/external_function_2.external-function.txt

For example
```solidity
contract C{
}
}
contract D is C{
}
}
contract E{
}
}
```
Will result in
```
f() should be declared external:
- C.f() (a.sol#2-4)
- D.f() (a.sol#8-10)
f() should be declared external:
- E.f() (a.sol#14-16)
```
The goal is to facilitate review of the finding. If the visibility is changed in the most derived contract, it must be changed in the base too. It will help the upcoming [slither-format](https://github.com/crytic/slither/pull/238) tool

Improve external function detector: merge together shadowed function

---

setup.py
slither/core/declarations/contract.py
slither/tools/flattening/__main__.py
slither/tools/flattening/flattening.py

Features:
- contract flattening
- export all most derived contracts, or a specific one
- `--convert-external`: change external to public (fix: https://github.com/crytic/crytic-compile/issues/32)
Missing:
- etherscan API
- some corner cases (ex: `Contract.enum`, ...)
- pragma
- tests
Fix #253. Replace #315

Add slither-flat

---

scripts/travis_test_embark.sh
scripts/travis_test_etherlime.sh

Node 12.x became the [new active node version](https://github.com/nodejs/Release#release-schedule), which breaks embark and etherlime

Use node 10.17.0 for embark and etherlime

---

slither/__main__.py
slither/tools/upgradeability/__main__.py
slither/tools/upgradeability/check_initialization.py
slither/tools/upgradeability/compare_function_ids.py
slither/tools/upgradeability/compare_variables_order.py
slither/utils/json_utils.py
tests/check-upgradeability/test_5.txt

This PR addresses #347 to add JSON output support for `slither-check-upgradability` tool as per the format specified in https://github.com/crytic/slither/wiki/JSON-output.
For now, it adds only the textual information which was being logged. Next step is to add source mapping and any more contextual information, as required.

Add JSON output for slither-check-upgradability tool

---

slither/detectors/attributes/incorrect_solc.py

This fixes the report that 0.5.11 is an old version.
This fixes #320

fix(detectors/attributes/incorrect_solc): report 0.5.11 as old version

---

scripts/travis_test_upgradability.sh
slither/core/declarations/contract.py
slither/tools/upgradeability/__main__.py
slither/tools/upgradeability/check_initialization.py
slither/tools/upgradeability/check_variable_initialization.py
slither/tools/upgradeability/compare_function_ids.py
slither/tools/upgradeability/compare_variables_order.py
slither/tools/upgradeability/constant_checks.py
tests/check-upgradeability/contract_v1_var_init.sol
tests/check-upgradeability/contract_v2_constant.sol
tests/check-upgradeability/test_1.txt
tests/check-upgradeability/test_10.txt
tests/check-upgradeability/test_11.txt
tests/check-upgradeability/test_2.txt
tests/check-upgradeability/test_3.txt
tests/check-upgradeability/test_4.txt
tests/check-upgradeability/test_5.txt
tests/check-upgradeability/test_6.txt
tests/check-upgradeability/test_7.txt
tests/check-upgradeability/test_8.txt
tests/check-upgradeability/test_9.txt

This PR contains several improvements on the upgradeability checks:
- Only the logic contract is needed, proxy becomes optional
- Change flag name [BREAKING CHANGE]
- Clean main to ease the add of new checks
- Clean variable ordering logic; merge the two function into one generic (fix #274)
- Refactor json output and add source mapping (fix #347). 
- Add check for constant conformance (fix #188)
- Overall output improvements
- Remove FP in case of fallback function collision (fix #331)
The json output and the constant conformance checks need to be tested. 
The documentation needs to be updated to merge this PR.

Refactor of slither-upgradeability-check

---

.dockerignore
Dockerfile

- install and run as normal user
- copy code from current directory, instead of installing from registry (might not be wanted?)
- add .dockerignore file, only ignores `Dockerfile` currently

feat: docker improvement

---

slither/detectors/variables/uninitialized_state_variables.py

Fix https://github.com/crytic/slither/issues/178

Uninitialized state variable detector: remove FP due to delegatecall proxy

---

README.md

Install by pip does not work in Macos

Updated pip3 for Macos

---

slither/slithir/convert.py

Fix #359
This is a temporary fix, the IR refactoring https://github.com/crytic/slither/pull/346 will change the way length-related operations are handled.

Add pop conversion 

---

slither/core/slither_core.py

I convert each element in source_mapping_elements with normpath() (collapses redundant separators and up-level references)
Now using regular expression search to see if pattern matches the src_mapping. Each pattern is run through method that handles relative paths.
I also broke up list comprehensions to multiple lines for readability

--filter-paths option now handles regex and relative paths

---

slither/tools/flattening/__main__.py
slither/tools/flattening/flattening.py
tests/flat/file1.sol
tests/flat/file2.sol

`slither-flat --remove-assert file.sol` will export the flattened code where the call to `assert()` are being commented.
A typical use case is the write of properties to be tested with echidna/manticore, that should not be present in the deployed code.
This must be used with precaution. All the `assert` that are commented are printed by the tool, and should be reviewed manually.
Fix  #366

slither-flat: add --remove-assert flag

---

slither/core/declarations/pragma_directive.py
slither/detectors/attributes/constant_pragma.py

This PR improves the handling of the pragma directive
- Add `is_solidity_version` property to Pragma object
- Filter constant pragma detector to solidity version only (fix #382)

Pragma: detect if the directive is a solidity version

---

slither/core/declarations/contract.py

Similar to `contract.functions_signatures` but for functions/variables that are declared by the contract

Add contract.functions_signatures_declared property

---

slither/analyses/data_dependency/data_dependency.py

`get_dependencies` incorrect used `only_unprotected`.
At first glance, this only affected the data dependency printer, and should not have impacted detectors
Fix #399

Fix get_dependencies

---

slither/detectors/variables/uninitialized_state_variables.py

Typical FP that this PR prevents: 
```solidity
contract C{
struct St{
bool init;
}
mapping(uint => St) map;
function set(St storage s) internal {
s.init = true;
}
function set() public{
set(map[0]);
}
}
```

Improve uninitialized-state: remove FPs due to storage variables

---

slither/core/cfg/node.py
slither/core/declarations/function.py
slither/formatters/naming_convention/naming_convention.py
slither/printers/summary/slithir.py
slither/slithir/operations/internal_call.py
slither/slithir/utils/ssa.py
slither/solc_parsing/declarations/function.py

- Instead of having a separate CFG, they are integrated within the original one
- This removes problems related to unreachable nodes, and some detectors' FPs
- Several corner cases regarding the IR conversion in the modifiers statements are removed
- `InternalCall` has now a property: `is_modifier_call`. In the long run, we might want to have a separate opcode for it
This changes the CFG generated and requires thorough tests

Change how modifier/constructor calls statements are handled

---

slither/slithir/convert.py

This PR updates the Delete operator to make its lvalue points to the original varible in case of ReferenceVariable.
This allows improving the SSA support for Delete

Improve Delete operator in case of ReferenceVariable

---

slither/all_exceptions.py
slither/core/declarations/contract.py
slither/core/slither_core.py
slither/detectors/all_detectors.py
slither/detectors/slither/name_reused.py
slither/slither.py
slither/solc_parsing/declarations/contract.py
slither/solc_parsing/exceptions.py
slither/solc_parsing/slitherSolc.py

Breaking change in the way Slither deals with codebase containing contracts with duplicate names:
- Add NameReused detector to report the name's reuse
- Slither will analyze the codebase that contains the issue, with partial context. As a result, the analysis might not be correct
Fix https://github.com/crytic/slither/issues/344

[WIP] Improve support for codebase with names' reuse

---

slither/core/cfg/node.py
slither/core/declarations/function.py
slither/solc_parsing/declarations/contract.py
slither/solc_parsing/declarations/function.py

This PR adds the support for:
- the new `receive()` fallback function
- the try/catch statements. One exception: variable shadowing between the catch statements and the definitions of the functions are not yet handled 
I dont have access to a large dataset of 0.6 contracts, so some edge cases might not be correctly parsed.

Improve support for 0.6

---

slither/slithir/convert.py
slither/solc_parsing/cfg/node.py

This PR fixes when this happens:
```
contract A{ constructor(uint) }
contract B is A {}
contract C is B{ constructor() A(10) B() {}
```
`C` calls `B()`, which does not exist. Slither incorrectly took `A.constructor` as the call's target.
This is a quick fix, a long term solution would be to check for the constructor's signature. Unfortunately, this information is not yet created when the conversion is done; the correct fix will require more work.

Fix constructor call if no constructor exist

---

slither/solc_parsing/expressions/expression_parsing.py

Example
```solidity
contract C{
function f(bytes memory data) public{
abi.decode(data, (address));
}
}
```

Fix incorrect parsing of abi.decode

---

slither/detectors/statements/divide_before_multiply.py

"integeer" -> "integer", removed "will"

Typos fixed in "Divide before multiply" detector description

---

slither/core/declarations/function.py
slither/detectors/slither/name_reused.py
slither/solc_parsing/declarations/contract.py
slither/solc_parsing/slitherSolc.py

In some cases, the contract is found but incorrect.
This PRs stops the IR generation in this situation, to prevent crashes during the IR analyses.

Improve support of codebase with contract's name reused

---

slither/core/expressions/call_expression.py
slither/core/expressions/member_access.py
slither/slithir/convert.py
slither/slithir/operations/member.py
slither/slithir/tmp_operations/tmp_call.py
slither/slithir/utils/ssa.py
slither/solc_parsing/expressions/expression_parsing.py
slither/visitors/expression/expression.py
slither/visitors/slithir/expression_to_slithir.py

For example:
```solidity
contract C {
function g(uint) external payable {}
function f(uint a) public payable {
this.g{value: 42, gas: 23+a}(10);
}
}
```
Generate now:
```
Expression: this.g{gas: 23 + a, value: 42}(10)
IRs:
TMP_0(uint256) = 23 + a
HIGH_LEVEL_CALL, dest:this(address), function:g, arguments:['10'] value:42 gas:TMP_0
```
Fix #419

Add suport for new call syntax: {gas: X, value: Y}

---

slither/core/declarations/contract.py
slither/core/declarations/function.py
slither/detectors/statements/controlled_delegatecall.py

- Add `function.all_nodes`
- Improve is_upgradeable_proxy by using all_nodes
- Improve controlled-delegatecall detector by using is_upgradeable_proxy (fix #420)

Improve report on upgradeable proxy codebase

---

scripts/tests_generate_expected_json_5.sh
slither/detectors/reentrancy/reentrancy.py
slither/detectors/reentrancy/reentrancy_benign.py
slither/detectors/reentrancy/reentrancy_eth.py
slither/detectors/reentrancy/reentrancy_events.py
slither/detectors/reentrancy/reentrancy_no_gas.py
slither/detectors/reentrancy/reentrancy_read_before_write.py
tests/expected_json/reentrancy-0.5.1-events.reentrancy-events.json
tests/expected_json/reentrancy-0.5.1.reentrancy-eth.json
tests/expected_json/reentrancy-0.5.1.reentrancy-eth.txt
tests/expected_json/reentrancy.reentrancy-eth.json
tests/expected_json/reentrancy.reentrancy-eth.txt
tests/expected_json/reentrancy.reentrancy-unlimited-gas.json
tests/expected_json/reentrancy.reentrancy-unlimited-gas.txt

This PR introduces `AbstractState` in the reentrancy detectors, which is a generic class to maintain the abstract representation used to detect reentrancy.
As a result, the reentrancy core was significantly refactored and the detectors are now able to show the calls/variables written from an internal call (fix https://github.com/crytic/slither/issues/421)
Additionally, python types were introduced in these detectors

Refactor reentrancy detectors

---

slither/core/declarations/function.py
slither/printers/guidance/echidna.py

- Do not report structure's name as constant
- Return `"()"` for fallback and receive functions
- Add python types

Improvement in echidna printer

---

slither/core/declarations/function.py
slither/printers/functions/cfg.py

- Create slithir_cfg_to_dot_str, which returns the dot content as a string
- Write the file in slithir_cfg_to_dot
This replaces #429

Improve slithir to dot functions

---

slither/utils/expression_manipulations.py

Example:
```solidity
contract C{
function f(bool a, bool b) public{
require(!a, b? "x" : "y");
}
}
```

Add support for ternary on unary operator

---

slither/solc_parsing/declarations/function.py

Example:
```solidity
contract C{
function f() external{
try this.f() {} catch {}
}
}
```

Fix parsing of empty catch statement

---

slither/printers/summary/human_summary.py

Calculates the number of lines of Solidity assembly and includes it in the human-summary printer output.
Resolves #395

Add assembly information to the human summary printer

---

examples/slither-prop/contracts/ERC20.sol
examples/slither-prop/contracts/Migrations.sol
examples/slither-prop/migrations/1_initial_migration.js
setup.py
slither/tools/properties/__main__.py
slither/tools/properties/addresses/address.py
slither/tools/properties/platforms/echidna.py
slither/tools/properties/platforms/truffle.py
slither/tools/properties/properties/erc20.py
slither/tools/properties/properties/ercs/erc20/properties/burn.py
slither/tools/properties/properties/ercs/erc20/properties/initialization.py
slither/tools/properties/properties/ercs/erc20/properties/mint.py
slither/tools/properties/properties/ercs/erc20/properties/mint_and_burn.py
slither/tools/properties/properties/ercs/erc20/properties/transfer.py
slither/tools/properties/properties/ercs/erc20/unit_tests/truffle.py
slither/tools/properties/properties/properties.py
slither/tools/properties/solidity/generate_properties.py
slither/tools/properties/utils.py
slither/utils/type.py

Features:
```
- Generate properties based on given scenarios. This PR includes ERC20 properties, for the  following scenarios
- Transferable - Test the correct tokens transfer
- Pausable - Test the pausable functionality
- NotMintable - Test that no one can mint tokens
- NotMintableNotBurnable - Test that no one can mint or burn tokens
- NotBurnable - Test that no one can burn tokens
- Burnable - Test the burn of tokens. Require the "burn(address) returns()" function
- Truffle support:
- Generation of the migration file
- Generation of unit tests files. For each scenario, one file test the correct initialization, and the second one contains the actual tests
- Echidna support
```

Add slither-prop tool: Automatic generation of unit-tests and Echidna properties

---

slither/core/declarations/function.py
slither/printers/guidance/echidna.py

Heuristic:
- If view/pure with Solidity >= 0.5 -> Return true
- If it contains assembly -> Return false (Slither doesn't analyze asm)
- Otherwise, check the rules from
https://solidity.readthedocs.io/en/v0.5.0/contracts.html?highlight=pure#view-functions
- One exception: internal dynamic calls are not correctly handled, so we consider them as non-constant

Echidna printer: improve constant function detection

---

slither/tools/upgradeability/utils/command_line.py

Such that `--list-detectors-json` for upgradeability follows the same standard than for the security issues

Upgradeabily: use 'check' instead of 'detector' in the json

---

slither/detectors/operations/block_timestamp.py

- Add support for "now" (close #430)
- Clean detector and use type annotation

Improvements in block.timestamp detector

---

slither/core/cfg/node.py
slither/core/declarations/function.py

And show true/false arrows in cfg export
Close #433
Example:
```solidity
contract C{
function f(bool b, bool c, bool d) public returns(uint){
if(b){
return 0;
}
else if(c){
return 1;
}
else{
if(d){
return 3;
}
return 2;
}
}
}
```
Note: this does not include IFLOOP statement

Node API: add true/false branchs for if statement 

---

slither/printers/summary/human_summary.py

Currently the human summary printer will run the detectors for each contract, instead of running them once.
As the result, the human summary printer can take a significant amount of time for large codebase

Human summary printer: run detectors only once

---

slither/__main__.py
slither/utils/command_line.py
slither/utils/output.py

- `--zip filename.zip` will export the json in a zip archive. The archive will contain one file named `"slither_results.json"`
- `--zip-type type` allows to change the compression. By default it uses lzma. It can be any of the [default python compression](https://docs.python.org/3/library/zipfile.html#zipfile-objects)
`--json` outputs a json with indentation, while in `--zip` the indentation is removed
For example, on a large codebase where the json is 14m (44m with the json indentation), the zip is 22k.

Add Zip export

---

slither/core/cfg/node.py
slither/core/declarations/function.py
slither/printers/guidance/echidna.py
slither/printers/summary/function_ids.py
tests/expected_json/incorrect_equality.incorrect-equality.json
tests/expected_json/incorrect_equality.incorrect-equality.txt
tests/expected_json/reentrancy-0.5.1-events.reentrancy-events.json
tests/expected_json/reentrancy-0.5.1-events.reentrancy-events.txt
tests/expected_json/unused_return.unused-return.json
tests/expected_json/unused_return.unused-return.txt
tests/possible_paths/paths.txt

0.6.11 introduced a bug with #445: The change in the function signature makes the parsing fails, as solc generates types using the contract's name rather than address in the json.
This PR:
- Reverts function.signature to return the name of the contract
- Adds function.solidity_signature that return the name with the contract converted. solidity_signature is used in the echidna and the function-ids printer
Fix #456, #457

Revert incorrect parsing introduced with 0.6.11

---

.github/workflows/ci.yml

This PR removes the etherscan test. The reason is that etherscan requires an API, which is provided as a github action private variable. As a result, PR from external users wont work anymore (example: https://github.com/crytic/slither/pull/459)
I will investigate how to prevent it, but in the meantime this test is disabled

Remove etherscan test

---

slither/printers/guidance/echidna.py
slither/slithir/variables/constant.py
slither/utils/arithmetic.py

`float` leads to a loss of precision for large number.
Fix #450

Use Decimal instead of float 

---

scripts/travis_test_printers.sh
slither/printers/functions/authorization.py
slither/printers/summary/data_depenency.py
slither/printers/summary/function.py
slither/printers/summary/function_ids.py
slither/printers/summary/modifier_calls.py
slither/printers/summary/require_calls.py
slither/printers/summary/variable_order.py
slither/tools/properties/__main__.py
slither/tools/upgradeability/utils/command_line.py
slither/utils/command_line.py
slither/utils/myprettytable.py
slither/utils/output.py

Add `MyPrettyTable`, to allow json seriliazation
This replaces https://github.com/crytic/slither/pull/459, the benefits are:
- It prevents adding new dependencies
- It standardize the pretty table usage. This allows to use the same serialization in slither's tools
- It's a bit more flexible; for example it will allow us in the future to add stuff like source mapping into the pretty table serialization if needed

Add wrapper around PrettyTable

---

slither/core/declarations/contract.py
slither/core/declarations/pragma_directive.py
slither/printers/summary/human_summary.py
slither/utils/standard_libraries.py
slither/utils/tests_pattern.py

- New APIs:
- utils.tests_pattern functions
- contract.is_test
- contract.is_token / contract.is_possible_token
- pragma.is_abi_encoder_v2
- Standard library: add support for @openzepeelin/contracts package
- Improve human summary printer:
- Use the added API
- Use MyPrettyTable
- Filter test contracts
- Add features column
- Send/receive eth
- selfdestruct
- delegatecall
- use assembly
- use ecrecover
- has external token interactions
- use abiencoderv2
- upgradeability

Add new APIs and improve human summary printer

---

slither/analyses/write/are_variables_written.py

The original algo in `are_variables_written` can lead to a long computation on functions with numerous if/then/else

Add better fixpoint on are_variables_written

---

slither/tools/similarity/cache.py

There was a numpy error while trying to run `slither-simil test` on a contract.
Changed the value for the argument `allow_pickle` in `numpy.load` from `False` to `True`.

Fixed numpy error while running slither-simil test command

---

slither/tools/flattening/flattening.py

slither-flat: Improve utf8 support and mapping/array lookup

---

slither/slithir/convert.py

Fix #481
Ex:
```solidity
interface I {
function f() external;
function g() external;
}
contract C{
function f() public pure returns(bytes4){
return type(I).interfaceId;
}
}
```

Add support for type(I).interfaceId

---

slither/tools/flattening/__main__.py
slither/tools/flattening/export/export.py
slither/tools/flattening/flattening.py

- Allow to specify a strategy (as defined in #495)
- `--strategy StrategyName`
- `MostDerived`: Export all the most derived contracts (every file is standalone)
- `OneFile`: Export all the contracts in one standalone file
- `LocalImport`: Export every contract in one separate file, and include `import ".."` in their preludes
- Default: `MostDerived`
- Add json and zip export
- `--json -` will output to stdout
- `--zip-type`: Zip compression type (default lzma)
- Clean up architecture
- Clean up logging and --help

Several improvements to slither-flat

---

slither/core/expressions/call_expression.py
slither/core/expressions/new_contract.py
slither/slithir/convert.py
slither/slithir/operations/new_contract.py
slither/slithir/tmp_operations/tmp_call.py
slither/slithir/tmp_operations/tmp_new_contract.py
slither/slithir/utils/ssa.py
slither/solc_parsing/expressions/expression_parsing.py
slither/visitors/expression/expression.py
slither/visitors/slithir/expression_to_slithir.py

The syntax (introduced in 0.6.2) was only supported for external calls.
Additionally, add support for `salt` parameter (fix #485)
Example:
```solidity
contract B{
constructor() public payable{}
}
contract C{
function f(B b) public returns(bytes4){
bytes32 s = bytes32(0);
uint v = 1;
new B{value: v, salt:s}();
}
}
```

Add support for new C{value:1} syntax

---

slither/core/declarations/contract.py
slither/solc_parsing/slitherSolc.py

- Internally create a contract named SlitherInternalTopLevelContractX per structure / enum
- Warm if user has a contract named SlitherInternalTopLevelContract
Fix #487

Add support for top level structures and enums

---

slither/core/cfg/node.py
slither/core/declarations/function.py
slither/solc_parsing/declarations/function.py

A minimal fix for #518. Just link the condition to the end after the body has been parsed

Fix ordering of sons when parsing for loop

---

slither/core/declarations/contract.py
slither/core/slither_core.py
slither/core/solidity_types/array_type.py
slither/core/solidity_types/elementary_type.py
slither/core/solidity_types/function_type.py
slither/core/solidity_types/mapping_type.py
slither/core/solidity_types/type.py
slither/core/solidity_types/user_defined_type.py
slither/printers/summary/variable_order.py
slither/solc_parsing/declarations/contract.py
slither/solc_parsing/slitherSolc.py

Since some contracts can be extended by more than one derived contract, storage layout information can't be stored in the state variable itself.
Also, `state_variables_ordered` had duplicates which seemed kinda weird so I "fixed" that.
Tested by reading [this doc](https://github.com/ethereum/solidity/blob/develop/docs/internals/layout_in_storage.rst) and comparing the output with `solc --storage-layout`, but some automated tests would probably be nice

Implement support for calculating storage layout

---

slither/visitors/slithir/expression_to_slithir.py

Use the type of the left variables to deduce the types of the tuple variables during the expression -> slithIR conversion.
This might not be enough if the types of the left variables are unknown at this step, but I am not sure that this situation can happen for tuples.
Fix #529

Improve type support for tuple 

---

slither/slithir/convert.py
slither/slithir/operations/low_level_call.py
slither/visitors/slithir/expression_to_slithir.py

The incorrect tuple types were only present for low level calls with solidity >= 0.5 (low level call return a tuple instead of a bool from 0.5)
Fix #529
Replace #536
Tested with
```solidity
library Lib{
function t() public returns(uint, bool){
}
}
contract Tuple {
function f()
public
{
bool success;
address dest;
bytes memory returnValue;
(success, returnValue) = dest.call("");
}
function get() internal returns(uint, bool);
function test() public{
uint a;
bool b;
(a,b) = get();
(a,b) = Lib.t();
}
}
```
```
Contract Tuple	Function Tuple.f() (*)
Expression: (success,returnValue) = dest.call()
IRs:
TUPLE_0(bool,bytes) = LOW_LEVEL_CALL, dest:dest, function:call, arguments:['']  
success(bool)= UNPACK TUPLE_0 index: 0 
returnValue(bytes)= UNPACK TUPLE_0 index: 1 
Function Tuple.get() (*) …
```

Fix incorrect tuple type in case of low level call

---

slither/core/solidity_types/type_information.py

The type was missing in https://github.com/crytic/slither/pull/507

Add storage_size for TypeInformation

---

slither/slithir/convert.py

Convert structure types to list of types if the lvalue is a tuple.
This specific case is needed in case an external call to a state variables that is a structure.
I haven't found other situations where tuples could appear from external calls, but I might have missed some cases.
Fix the second issue raised in https://github.com/crytic/slither/issues/529.
Tested on 
```solidity
library Lib{
function t() public returns(uint, bool, uint){
}
}
contract Called{
function f() public returns(uint, bool, uint);
struct St{
uint a;
bool b;
uint c;
}
St[] public sts;
}
contract Tuple {
function test_low_level()
public
{
bool success;
address dest;
bytes memory returnValue;
(success, returnValue) = dest.call("");
(, returnValue) = dest.call("");
}
function get() internal returns(uint, bool, uint); …
```

Improve tuple handling

---

slither/core/expressions/elementary_type_name_expression.py
slither/slithir/convert.py
slither/slithir/operations/solidity_call.py
slither/solc_parsing/declarations/function.py
slither/solc_parsing/expressions/expression_parsing.py
slither/visitors/slithir/expression_to_slithir.py

`abi.decode`:
- Better IR output
- Propagate types (fix #529 third case)
- Correct parsing in abi.decode parameters in case of arrays
Tuples:
- Improve support of tuple singleton (the generated IR was missing an
Unpack operation)
Tested with
```solidity
contract Test{
function g() internal returns(uint,uint,uint) ;
function f(bytes calldata data) external {
(address a, uint b, uint c) = abi.decode(data, (address, uint256, uint256));
(address d,uint[] memory k,) = abi.decode(data, (address, uint256[], uint256));
(uint e,,) = (1,2,3);
(uint f,,) = g();
}
}
```
```
Expression: (a,b,c) = abi.decode(data,(address,uint256,uint256))
IRs:
TUPLE_0(address,uint256,uint256) = SOLIDITY_CALL abi.decode()(data(address,uint256,uint256))
a(address)= UNPACK TUPLE_0 index: 0 
b(uint256)= UNPACK TUPLE_0 …
```

Several improvements in tuples and abi.decode support

---

slither/solc_parsing/expressions/expression_parsing.py

This PR converts array slices to direct array access. 
While the generated IR will be incorrect, it will allow Slither to continue its analyses.
We will need additional investigations to evaluate how to better support the arrays slices at the IR level.

Temporary support for array slices

---

slither/slithir/convert.py

Example:
```Solidity
contract C{
function f(bytes calldata a) public{
uint b = abi.decode(a, (uint));
}   
}
```
```
TMP_0(uint256) = SOLIDITY_CALL abi.decode()(a,uint256)
b(uint256) := TMP_0(uint256)
```

Improve abi.decode support in case of single type to convert

---

slither/detectors/reentrancy/reentrancy_events.py

`variable.name` is now a `Constant`, which lacks the ordering operator

Fix missing str conversion on reentrancy event

---

slither/visitors/slithir/expression_to_slithir.py

A bug was introduced with #548: if a tuple variable was re-assign in a standard expression, the IR conversion would try to convert the expression to an UNPACK operation:
```solidity
contract C{
function r() public returns(uint, uint){
}
(uint a, uint b) = r();
a = 10;
}
}
```

Fix incorrect handling of tuple variable re-assignement

---

slither/core/declarations/solidity_variables.py
slither/slithir/convert.py

Solidity 0.6.8 changed the function signature from `type(address)`  to `type()` 
Fix #547

Improve support for type()

---

slither/solc_parsing/yul/parse_yul.py

Forgot to check state variables during resolution. Fixes #574.
Testcase:
```solidity
contract Parent {
uint internal constant a = 5;
}
contract Child is Parent {
function test() public view returns (uint x) {
assembly {
x := a
}
}
}
```

Resolve state variables in Yul

---

slither/slithir/convert.py

The tuple resulting from a high level calls to a structure, where the structure has mapping or array will not contain the mapping or array.
Example
```solidity
contract A{
struct St{
uint a;
uint b;
mapping(uint => uint) map;
uint[] array;
}
mapping (uint => St) public st;
}
contract B{
function f(A a) public{
(uint a, uint b) = a.st(0);
}
}
```

Fix incorrect types to list conversion

---

scripts/travis_test_embark.sh
scripts/travis_test_etherlime.sh
scripts/travis_test_truffle.sh
slither/detectors/attributes/incorrect_solc.py
tests/expected_json/old_solc.sol.json.solc-version.txt
tests/expected_json/solc_version_incorrect.solc-version.json
tests/expected_json/solc_version_incorrect.solc-version.txt
tests/expected_json/solc_version_incorrect_05.ast.json.solc-version.json
tests/expected_json/solc_version_incorrect_05.ast.json.solc-version.txt

New versions recommended:
- 0.5.11 - 0.5.13
- 0.5.15 - 0.5.17
- 0.6.8
- 0.6.10 - 0.6.11
Additionally the text generated with the issue was improved. This will lead to prevent previously triaged `solc-version` issues to not be recognized.
Fix #57

Update solc recommended versions

---

README.md
slither/slithir/variables/constant.py
slither/tools/erc_conformance/__main__.py

Fixes issue #579.
The issue was that slither was computing 10**HUGE_NUMBER eagerly in order to multiply it with the first part of the scientific notation.... which takes a while, and eats up lots of memory, because we're using bignums for this. I changed the behavior so that, if the first part is zero, just return zero. Otherwise, if the exponent is greater than 80, raise a ValueError, because there's no way the result will fit into a solidity integer type unless they're just writing it out in a really really troll-y way.
This will raise on something like `0.{80 zeros}1E80`. Not sure if solc supports that, but if we wanted to, we could add some sort of behavior with alternately multiplying the base by 10 and decrementing the exponent until it's zero... but that'd require some checks too …

Fixing DOS large exponent in scientific notation constants.

---

slither/slithir/convert.py

Bug that was introduced with https://github.com/crytic/slither/pull/600
```solidity
contract C{
function f() public;
function g() public{
this.f();
}
}
```
Would have resulted to an internal dynamic call, instead of a high level call

Fix incorrect conversion for this.call()

---

slither/solc_parsing/declarations/function.py

solidity started stripping null members it seems. this might not be the only thing that's broken, but I guess we can fix them as we stumble across them.
repro case:
```
solc, the solidity compiler commandline interface
Version: 0.7.0+commit.9e61f92b.Linux.g++
```
```solidity
contract C {
function f() public {
if (0 > 0) {
0;
}
}
}
```

fix if statement handling for solc 0.7.0+

---

slither/printers/functions/cfg.py

before:
```
INFO:Printers:Export C-doubleAndAdd(uint256,uint256).dot
Export C-doubleAndAdd(uint256,uint256).dot-C-test().dot
Export C-doubleAndAdd(uint256,uint256).dot-C-test().dot-C-slitherConstructorVariables().dot
```
after:
```
INFO:Printers:Export C-doubleAndAdd(uint256,uint256).dot
Export C-test().dot
Export C-slitherConstructorVariables().dot
```

fix cfg printer filename generation

---

slither/solc_parsing/yul/parse_yul.py

Add a unique name for yul variables to prevent lookup issue (fix #647)
Testcase:
```
contract C{
if(true) {
assembly{
let a := 10
for {} true {} {
a := add(a, 1)
}
}
}
else{
assembly{
let a := 10
for {} true {} {
a := add(a, 1)
}
}
}
}
}
```

Use unique variable name for yul variable

---

slither/core/declarations/contract.py

A small simplification of `Contract.ercs` function and some `all(...)` calls.
FWIW the second change doesn't really change the performance of the code etc. as the `all((x for x in y))` boils down to the same bytecode as `all(x for x in y)` under the hood:

Simplify Contract code

---

slither/core/source_mapping/source_mapping.py

Use `get_line_from_offset` introduced in https://github.com/crytic/crytic-compile/pull/130
Related: https://github.com/crytic/slither/issues/695

Use get_line_from_offset from crytic_compile in source mapping 

---

slither/detectors/statements/divide_before_multiply.py

The detector was crashing on long functions due to the recursion limit

Remove recursion in divide-before-multiplity

---

slither/detectors/statements/boolean_constant_misuse.py
tests/detectors/boolean-constant-misuse/boolean-constant-misuse.sol
tests/detectors/boolean-constant-misuse/boolean-constant-misuse.sol.0.6.0.BooleanConstantMisuse.json
tests/test_detectors.py

PR involves: 
- Collapsing branch conditions into single if statement 
- Removed `# pylint: disable=too-many-nested-blocks`
- 100% coverage on `boolean-constant-misuse` detector

Added tests for boolean-constant-misuse

---

slither/slither.py

When using CryticCompile (the "default"), `self.filename` will not be set, but is passed into each printer. Due to this, executing the `inheritance-graph` and `call-graph` printers will result in files with the default name, `contracts` and `all_contracts`, respectively. Instead of using the name of the Solidity file. Example on `Migrations.sol`:
```
INFO:Printers:Call Graph: all_contracts.dot
Call Graph: Migrations.dot
INFO:Printers:Inheritance Graph: contracts.dot
```
With the fix of this PR applied the result will instead be:
```
INFO:Printers:Call Graph: Migrations.sol.dot
Call Graph: Migrations.dot
INFO:Printers:Inheritance Graph: Migrations.sol.dot
```

fix set `self.filename` when using crytic-compile

---

slither/printers/call/call_graph.py
slither/printers/inheritance/inheritance_graph.py

fixes issue #727 
depends on PR #726 to be merged, otherwise the `filename` argument will be an empty string.
example: `slither Contract.sol --print call-graph,inheritance-graph`
```
INFO:Printers:Call Graph: Contract.sol.all_contracts.call-graph.dot
Call Graph: Contract.sol.SafeMath.call-graph.dot
Call Graph: Contract.sol.Contract.call-graph.dot
INFO:Printers:Inheritance Graph: Contract.sol.inheritance-graph.dot
```

Add more descriptive names to inheritance-graph + call-graph printers outputted files

---

slither/core/expressions/member_access.py
slither/solc_parsing/expressions/expression_parsing.py

Undo part of https://github.com/crytic/slither/pull/730
Currently `parse_type` is too weak to handle all the types from a memberAccess, we should consider rewriting this function to be cleaner and more robust.

Disable parsing types on memberAccess

---

CONTRIBUTING.md
slither/core/declarations/function.py
tests/test_function.py
tests/test_function.sol

Given a function that can not send ether but can reenter:
```solidity
function reenter() public {
msg.sender.call("");
}
```
```python
f = Slither(...).contracts...functions
assert f.can_reenter()
assert not f.can_send_eth()
```
The second assertion will fail.
Looks like a copy & paste error.
this PR fixes that and adds tests for regression as well as most of the codomain of many other properties and getters of `slither.core.declarations.Function`.
The tests revealed that for a function `f` with visibility `pure`, `f.view` will return `True`.
Is this correct?

Fix that Function.can_send_eth() wrongly returns self._can_reenter. add tests for this and other properties and getters of Function class

---

README.md

As far as I know, slither works fine in Hardhat projects, but since it's not indicated on the readme people often ask about it on our discord.

Add hardhat to the list of supported projects

---

scripts/ci_test_etherlime.sh
slither/detectors/attributes/incorrect_solc.py
slither/detectors/statements/array_length_assignment.py

Remove false positive on array length detector

---

slither/solc_parsing/expressions/expression_parsing.py

These are two hotfixes to better support Solidity 0.8.
I am expecting more changes to be required, and we need to investigate more AST modifications with 0.8, but I wanted both fixes to be included in today's release
Fix (partially)
- https://github.com/crytic/slither/issues/794
- https://github.com/crytic/slither/issues/814
Related: 
- https://github.com/crytic/slither/issues/795

Improve parsing of Solidity 0.8

---

slither/core/declarations/__init__.py
slither/core/declarations/contract.py
slither/core/solidity_types/elementary_type.py
slither/slithir/convert.py
slither/slithir/operations/library_call.py
tests/ast-parsing/library_implicit_conversion-0.4.0.sol
tests/ast-parsing/library_implicit_conversion-0.5.0.sol

Slither was incorrectly converted some of the types in case of implicit conversion on library lookup
Ex:
```solidity
library Lib{
function t(uint, uint8) internal returns(uint){
return 0x1;
}
function t(uint, uint256) internal returns(uint){
return 0x32;
}
}
contract Test{
function test() public view returns(uint){
uint a;
return a.t(0x10);
}
}
````
The IR would incorrectly uses `t(uint, uint256)`.

Fix incorrect type conversion in case of libraries lookup name collision

---

slither/core/slither_core.py
slither/slithir/variables/reference.py
slither/slithir/variables/temporary.py
slither/slithir/variables/tuple.py
tests/detectors/uninitialized-fptr-cst/uninitialized_function_ptr_constructor.sol.0.5.8.UninitializedFunctionPtrsConstructor.json

The globally shared COUNTERs lead to generating different IRs if the same codebase was analyzed through different `Slither` objects, but within the same python env
Additionally this PR adds missing python types

Remove COUNTER from class

---

scripts/ci_test_printers.sh
slither/printers/summary/variable_order.py

Fix variable order printer

---

slither/core/declarations/function.py

This PR makes `onlyOwner` to be considered as a safe modifier.
While I think we should avoid hardcoding behaviors based on function/modifier name, I have tried a couple of different heuristics to improve `is_protected`, based on #401 ideas, but in the end none is as effective as just using the modifier name. 
If `onlyOwner` is incorrectly implemented, this PR will make Slither incorrectly assume that the function is protected. 
Overall I think this is a tradeoff that we can follow: we have a couple of detectors that can catch incorrect `onlyOwner`, and if someone tries to add a backdoor, he will have other ways to fool Slither anyway. 
The benefits of using this approach (removing multiple FPs) outweigh the downsides I think.
Fix #401

Relax is_protected heuristic

---

slither/detectors/variables/function_init_state_variables.py

Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#function-initializing-state-variables is invalid

updated reference wiki address

---

setup.py

Originally, `docker build` failed with the below error. Setting LANG or PTYHONIOENCODING did not help.
```
$ python3 setup.py install --user
Traceback (most recent call last):
File "setup.py", line 19, in <module>
long_description=open("README.md").read(),
File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 20401: ordinal not in range(128)
```

docker build success

---

slither/printers/call/call_graph.py

It fixes the filename of diagrams generated by `call-graph` printer.
Before: `..all_contracts.call-graph.dot`
After: `all_contracts.call-graph.dot`

fixed call-graph printer output filename

---

slither/tools/flattening/flattening.py

The options --convert-external and --convert-private are currently
broken from what looks like some automatic conversion according to git
blame.
Also fixes issue #580

Fix slither-flat external/private options

---

slither/detectors/all_detectors.py
slither/detectors/statements/delegatecall_in_loop.py
tests/detectors/delegatecall-loop/0.4.25/delegatecall_loop.sol
tests/detectors/delegatecall-loop/0.4.25/delegatecall_loop.sol.0.4.25.DelegatecallInLoop.json
tests/detectors/delegatecall-loop/0.5.16/delegatecall_loop.sol
tests/detectors/delegatecall-loop/0.5.16/delegatecall_loop.sol.0.5.16.DelegatecallInLoop.json
tests/detectors/delegatecall-loop/0.6.11/delegatecall_loop.sol
tests/detectors/delegatecall-loop/0.6.11/delegatecall_loop.sol.0.6.11.DelegatecallInLoop.json
tests/detectors/delegatecall-loop/0.7.6/delegatecall_loop.sol
tests/detectors/delegatecall-loop/0.7.6/delegatecall_loop.sol.0.7.6.DelegatecallInLoop.json
tests/detectors/delegatecall-loop/0.8.0/delegatecall_loop.sol
tests/detectors/delegatecall-loop/0.8.0/delegatecall_loop.sol.0.8.0.DelegatecallInLoop.json
tests/test_detectors.py

Based on #921:
- Update to the latest dev
- Use a branch instead of a remote repo for convenience

Add detector delegatecall inside a loop

---

slither/solc_parsing/expressions/find_variable.py

The reason is that this function is now called early on (before the contract is properly constructed), which can break the memoization

Do not use available_functions_as_dict in find_variable

---

slither/core/cfg/node.py
slither/detectors/statements/write_after_write.py

- `node.all_slithir_operations` could lead to an infinite loop due to modifying the loop variable
- `write_after_write` should not include tuple variable

Multiple minor fixes

---

slither/core/slither_core.py

"show_ignore_findings" calls itself instead of returning a similar named variable.
This causes an infinite recursion, resulting in an RecursionError when creating a Slither Object via the Python API

Fixed infinite recursion in show_ignore_findings

---

.github/workflows/features.yml
slither/visitors/expression/constants_folding.py
tests/constant_folding_unary.sol
tests/test_constant_folding_unary.py

Closes #1080 
I added support for in our constant folding for when a negative constant, `int a = -7` is negated `x[-a]`.

Support unary operation, MINUS_PRE, on constants

---

slither/core/declarations/contract.py
slither/utils/erc.py

This PR add the support of [ERC4626](https://eips.ethereum.org/EIPS/eip-4626), [ERC2612](https://eips.ethereum.org/EIPS/eip-2612) for slither-check-erc tool.

Add support of ERC4626, ERC2612 for slither-check-erc

---

.github/workflows/ci.yml

Recently embark has made our CI not reliable. However, not a lot of projects are still using embark. This PR disable embark from our CI until we figure out how to fix it.
Related: https://github.com/crytic/slither/pull/1124
It might be related to https://github.blog/2021-09-01-improving-git-protocol-security-github/

Disable embark CI

---

slither/core/declarations/contract.py
slither/solc_parsing/solidity_types/type_parsing.py
slither/tools/flattening/__main__.py
slither/tools/flattening/flattening.py

- Better support of multiple compilation unit
- Better support if there are multiple contracts with the same name
- Better support of top level object (partially fix #955). The support
for the local import strategy is missing
There are still bugs in `slither-flat` (ex: sometimes the exported libraries are missing the `library` keyword), and this needs further investigation

Improve slither-flat

---

slither/printers/guidance/echidna.py

Create two new fields `with_fallback`/`with_receive`. Ex:
```solidity
contract A{
}
contract B{
fallback() external{}
function f() public{}
}   
contract C{
fallback() external{}
receive() external payable{}
}   
```
```
"with_fallback": [
"B",
"C"
],
"with_receive": [
"C"
]
```

Add fallback/receive info to echidna printer

---

slither/__main__.py
slither/detectors/attributes/constant_pragma.py
tests/detectors/pragma/0.4.25/pragma.0.4.25.sol.0.4.25.ConstantPragma.json
tests/detectors/pragma/0.5.16/pragma.0.5.16.sol.0.5.16.ConstantPragma.json
tests/detectors/pragma/0.6.11/pragma.0.6.11.sol.0.6.11.ConstantPragma.json
tests/detectors/pragma/0.7.6/pragma.0.7.6.sol.0.7.6.ConstantPragma.json

Fixes "Different versions of Solidity is used" -> "Different versions of Solidity are used" in slither output.
Also fixes the same string being used for comparisons in tests but I wasn't able to figure out how to run all the tests locally, I guess CI will run those checks for me..
I was able to run individual suites w specific calls into scripts eg `bash scripts/ci_test_data_dependency.sh` but some of these have suspicious output & still exit w code 0. I expected `bash scripts/ci_test.sh` to run all test suites w a clear indication when something failed but it exits w/out any output & exit code 0.. Maybe that means everything works as expected?

fix typo in output

---

.github/ISSUE_TEMPLATE/feature_request.yml
.github/workflows/black.yml
.github/workflows/ci.yml
.github/workflows/detectors.yml
.github/workflows/features.yml
.github/workflows/linter.yml
.github/workflows/parser.yml
.github/workflows/pip-audit.yml
.github/workflows/pylint.yml
scripts/ci_test_dapp.sh
slither/core/slither_core.py
tests/.gitattributes
tests/test_detectors.py

This PR introduces Windows into Slither's CI workflows. In the process of doing so, it also fixes several issues that affect execution of Slither and/or tests in the Windows OS.

Windows CI for Slither

---

.github/workflows/black.yml
.github/workflows/ci.yml
.github/workflows/detectors.yml
.github/workflows/features.yml
.github/workflows/linter.yml
.github/workflows/parser.yml
.github/workflows/pylint.yml
CONTRIBUTING.md
setup.py
slither/core/solidity_types/elementary_type.py
slither/detectors/attributes/unimplemented_interface.py
slither/detectors/naming_convention/naming_convention.py
slither/detectors/source/rtlo.py
slither/detectors/statements/type_based_tautology.py
slither/slithir/convert.py
slither/solc_parsing/yul/parse_yul.py
slither/utils/integer_conversion.py
slither/visitors/expression/constants_folding.py

This PR cleanup our CI to use a fix version of gh super linter, to avoid
breaking the CI on new super linter release. Additionally it update our linters, the new versions:
- pylint 2.13.4
- black 22.3.0
Similar to https://github.com/crytic/crytic-compile/pull/252

Update to gh super linter 4.9.2 + linters

---

.github/ISSUE_TEMPLATE/bug_report.yml

The "Relevant log output" wasn't rendering as a code snippet due to some extra indentation

fix shell rendering in bug report template

---

slither/core/declarations/function.py

`Function.__str__` used to return `self._name`. However, for special function types this value can be `None`, which causes `__str__` to raise a `TypeError` at runtime. This small change uses `self.name` instead, which is a property that returns valid strings for all special function types.
Fixes #1170

Prevent a TypeError on Function.__str__

---

slither/detectors/statements/too_many_digits.py

Quick benchmarks (reusing values from https://github.com/ethereum/eth-utils/pull/223/commits/f0139f0d4e98370344a27254b777f7e62ac260f2, I know TX hash is irrelevant here, but results should be the same for addresses):
- When `value` is hexadecimal string (TX hash):
- before: 1.0965 sec
- after : 0.3652 sec (-66.7 %)
- When `value` is not hexadecimal string (TX hash + 'g'):
- before: 1.4546 sec
- after : 0.7022 sec (-51.7 %)

Optimization: use a more efficient regexp for hexadecimal check

---

slither/slither.py

Few days ago, when I was trying to pass the `solc` compiling options to `Slither` by using the argument `solc_args`, e.g., `Slither(my_contract, solc_arguments=my_args)`, it did not function. I checked the `crytic-compile` source code and found that the argument `crytic-compile` actually takes is `solc_args` instead of `solc_arguments`, as the link [here](https://github.com/crytic/crytic-compile/blob/master/crytic_compile/platform/solc.py#L232) and following code segment shows. The argument annotation in slither.py is wrong and it will mislead developers to pass the `solc` compiling options with wrong keys.
```python
solc: str = kwargs.get("solc", "solc")
solc_disable_warnings: bool = kwargs.get("solc_disable_warnings", False)
solc_arguments: str = kwargs.get("solc_args", "")
solc_remaps: …
```

Fix Wrong Argument Annoations in Slither

---

slither/utils/output.py

Do not fail with no results and sarif output

---

.github/workflows/ci.yml
scripts/ci_test_kspec.sh
scripts/ci_test_simil.sh
slither/__main__.py
slither/utils/colors.py
tests/check-kspec/test_1.txt
tests/check-upgradeability/test_1.txt
tests/check-upgradeability/test_10.txt
tests/check-upgradeability/test_11.txt
tests/check-upgradeability/test_2.txt
tests/check-upgradeability/test_3.txt
tests/check-upgradeability/test_4.txt
tests/check-upgradeability/test_5.txt
tests/check-upgradeability/test_6.txt
tests/check-upgradeability/test_7.txt
tests/check-upgradeability/test_8.txt
tests/check-upgradeability/test_9.txt

Color escape codes are most likely not expected if piping the output
of slither into a file or other tool. Check if stdout is a tty before
enabling colored output.
Additionally, fix Windows tests which were failing due to a cygwin conflict
and text encoding differences.

Disable coloring if output is not a terminal, fix Windows tests

---

slither/__main__.py
slither/tools/erc_conformance/erc/ercs.py

Remove unnecessary Check event

---

slither/detectors/statements/unprotected_upgradeable.py
slither/tools/upgradeability/checks/initialization.py
tests/detectors/uninitialized-state/0.4.25/uninitialized.sol
tests/detectors/uninitialized-state/0.5.16/uninitialized.sol
tests/detectors/uninitialized-state/0.6.11/uninitialized.sol
tests/detectors/uninitialized-state/0.7.6/uninitialized.sol
tests/detectors/unprotected-upgrade/0.4.25/Buggy.sol.0.4.25.UnprotectedUpgradeable.json
tests/detectors/unprotected-upgrade/0.5.16/Buggy.sol.0.5.16.UnprotectedUpgradeable.json
tests/detectors/unprotected-upgrade/0.6.11/Buggy.sol.0.6.11.UnprotectedUpgradeable.json
tests/detectors/unprotected-upgrade/0.7.6/Buggy.sol.0.7.6.UnprotectedUpgradeable.json

WIP, though, and would like advising--when replacing all instances, 4 related tests fail.
Advice on how to get those tests passing to get this corrected welcome.
```python
~/code/forks/slither$ pytest ./tests/test_detectors.py
========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.9.5, pytest-7.1.1, pluggy-1.0.0
rootdir: /home/kyle/code/forks/slither
plugins: mock-3.7.0, cov-3.0.0
collected 291 items                                                                                                                                                                                      
tests/test_detectors.py …
```

correct instances of typo throughout repo: initiliaze -> initialize

---

Dockerfile

It fixes the following Python error when running slither:
```
AttributeError: module 'typing' has no attribute '_SpecialForm'
```

Dockerfile: upgrade from Ubuntu Bionic (18.04) to Focal (20.04)

---

README.md
slither/detectors/assembly/shift_parameter_mixup.py
slither/detectors/variables/similar_variables.py

Some of the anchor links reported by Slither do not work.
The docs have probably changed overtime, but the links were not edited in the README and the python scripts.
Edited two incorrect anchor links in the README and the Python scripts.

fix: anchor links to Vulnerability report docs

---

slither/core/slither_core.py

Path filtering is performed on absolute paths, which causes regexps
to not work uniformly across OSes, due to the different path separator
(forward vs backward slashes). This converts paths to POSIX-style
before filtering, so that regexps can be written in a single style
and work across all systems.
Fixes: #1191

Unify path filtering across POSIX and Windows

---

slither/solc_parsing/declarations/contract.py
slither/tools/flattening/flattening.py

The assignment was wrong, leading `contract_kind` to be never set.
This PR also includes https://github.com/crytic/slither/pull/1297, which is where the bug was found

Fix contract_kind

---

slither/core/slither_core.py

Follow up on https://github.com/crytic/slither/pull/935

Handle ignore markers when exclude-dependencies is set

---

slither/core/slither_core.py

`valid_results` behaviour is described in terms of "results are valid,
unless ...".  A matching implementation would be to only return `True` a
the end of the function, and have all the cases only return `False` if
they detect an invalid result.
`show-ignored-findings` is the only exception to the rule above.

Handle ignore markers when `exclude-dependencies` is set

---

.github/workflows/docker.yml
Dockerfile

This PR:
* updates the Dockerfile base to Ubuntu Jammy (22.04)
* separates build and install processes into two stages
* replaces fixed solc binary with solc-select
* adds a workflow that builds the container for
*  linux/amd64 (x86_64 systems),
*  linux/arm64 (ARM 64-bit systems, eg. Mac M1 with Docker Desktop)
*  linux/arm/v7 (ARM 32-bit systems, eg. some SBC systems)
* publishes the container on GHCR:
* matching tagged builds for tag releases,
* `edge` tag matching the latest `master` commit
* `latest` tag matching the latest release
* `testing-foo` matching the latest commit in branch `foo` (must be also enabled in the workflow `on: ..` section)
Closes: #937, #1330

Update Dockerfile and add Actions workflow to build it

---

setup.py

Added long_description_content_type value to have Pypi website correctly
render Readme.md with markdown
Fixes #1287

Fixed Pypi Markdown render

---

slither/core/expressions/literal.py

Fixes https://github.com/crytic/slither/issues/1286
IR generated after this PR:
```
Contract Setter
Function Setter.set(uint256[1],uint256,uint256) (*)
Expression: self[key] = value
IRs:
REF_0(uint256) -> self[key]
REF_0 (->self) := value(uint256)
Contract SetterTest
Function SetterTest.f(uint256,uint256) (*)
Expression: params.set(key,value)
IRs:
LIBRARY_CALL, dest:Setter, function:Setter.set(uint256[1],uint256,uint256), arguments:['params', 'key', 'value'] 
```

implement eq for literal

---

slither/core/declarations/function.py
slither/utils/type.py
tests/function_ids/rec_struct-0.8.sol
tests/test_features.py

Hotfix to support recursive type

Use full_name for solidity signature in case of internal function

---

scripts/ci_test_cli.sh
scripts/ci_test_truffle.sh
slither/__main__.py
slither/utils/command_line.py

This PR adds the `--no-fail-pedantic` flag, which is the opposite of `--fail-pedantic`. It also changes the default which is now to set `--fail-pedantic` to `True`.

Add the `--no-fail-pedantic` flag

---

Dockerfile

This assists in running x86_64 dynamic binaries, such as certain solc 0.8.x releases, in ARM containers. This can be useful when working on machines with certain emulation configuration, such as M1 Macs with Docker Desktop.

Dockerfile: add x86_64 libc on non-intel containers

---

slither/tools/read_storage/README.md
slither/tools/read_storage/__main__.py

Little tweak that updates `slither-read-storage` docs to no longer reference the depreciated `--layout` cli arg

update readme & usage message to reference up-to-date flags

---

setup.py
slither/detectors/attributes/incorrect_solc.py

https://github.com/crytic/slither/pull/1389 changed the recommended solc versions but did not update the version text

fix: text for too recent version

---

slither/detectors/abstract_detector.py

Closes https://github.com/crytic/slither/issues/1354, https://github.com/crytic/slither/issues/922, https://github.com/crytic/slither/issues/885
Right now, all of the prompts do not show until the last result is output... adding a new line makes a prompt show for each detectors' results (idk why this is).

fix triage prompt not displaying

---

slither/detectors/variables/possible_const_state_variables.py

Presently the constants detector does not detect Contract types.
Eg.
```
IERC20 public token = IERC20(0x0000000000000000000000000000000000000000);
```
This is not a big deal as hardcoding addresses like that is generally an anti-pattern. However, if someone ever forks the detector for immutable flagging, than this will definitely come in handy!
Please do test before merging: we use the slither python API and not the detector framework ourselves.
This pull request specifically checks that if the candidate type is not Elementary, it must be a user defined Contract.
Let us know if it makes sense to invert the check and perhaps focus on ignoring dynamic types instead (because this PR still doesn't catch const enums I think for example, or re-typed int's, though that's also easily extendable)

Constants detector: Also detect Contract types

---

slither/tools/read_storage/read_storage.py

it should be used over `(state_)variables` as it includes inherited, private variables, too. fixes #1322

use state_variables_ordered  API

---

setup.py
slither/printers/summary/function_ids.py
slither/utils/function.py

move to a maintained package. also will probably help reduce namespace conflicts e.g. https://github.com/crytic/slither/issues/1218

(deps) replace pysha3 with pycryptodome

---

slither/detectors/abstract_detector.py
slither/detectors/compiler_bugs/enum_conversion.py

addresses #1476 
precursor to #1424

refactor: add VULNERABLE_SOLC_VERSIONS and logic

---

slither/__main__.py
slither/detectors/functions/codex.py
slither/slither.py
slither/utils/command_line.py

Highlights of this pr:
- Parameterize the inputs to the OpenAI codex call: `model`, `temperature`, and `max_tokens`
- Add `--codex-contracts` argument which takes a comma-delimited list of contracts and, if specified, it will limit the Codex detector to only those contracts.  I found this a great way to save money when working with a large contract with a deeply nested inheritance tree.  Someday, may want to expand this feature to all detectors.
- It also changes the prompt to something I was having more luck with.  It no longer asks a "Yes" or "No" question, so the prompt now also requires the use of a keyword if vulns are found.
I did spend some time implementing a "retries" system.  But for some reason, the retried "queries" were all identical.  I guess I was hoping it would exhibit …

feat: Codex vuln detector -  devtooligan updates

---

setup.py
slither/__main__.py
slither/detectors/all_detectors.py
slither/detectors/functions/codex.py
slither/slither.py
slither/utils/codex.py
slither/utils/command_line.py

The detector requires:
- The user set the flag `--codex` (meaning that codex is not ran by default)
- `openai` must be installed, and `OPENAI_API_KEY` set
The detector works at the contract level, and send the whole contract body to codex

Add Codex vuln detector

---

slither/detectors/naming_convention/naming_convention.py
tests/detectors/naming-convention/0.4.25/naming_convention.sol
tests/detectors/naming-convention/0.4.25/naming_convention.sol.0.4.25.NamingConvention.json
tests/detectors/naming-convention/0.5.16/naming_convention.sol
tests/detectors/naming-convention/0.5.16/naming_convention.sol.0.5.16.NamingConvention.json
tests/detectors/naming-convention/0.6.11/naming_convention.sol
tests/detectors/naming-convention/0.6.11/naming_convention.sol.0.6.11.NamingConvention.json
tests/detectors/naming-convention/0.7.6/naming_convention.sol
tests/detectors/naming-convention/0.7.6/naming_convention.sol.0.7.6.NamingConvention.json

The regex `^[lOI]$` inside `should_avoid_name()` will only match on the single letter variables `l`, `O`, or `I`, which are not recommended by the [style guide](https://docs.soliditylang.org/en/v0.8.17/style-guide.html#names-to-avoid). 
The inner `not is_upper_case_with_underscores()` check is unnecessary and also allows the single letter variables `O` and `I` to pass.
Fixes #1418

Fix `naming-convention` to flag single letter `O` or `I` variable

---

slither/core/declarations/solidity_variables.py
slither/slithir/convert.py

abi.encodeCall is not supported as a `SolidityFunction`/`SolidityCall`. This adds support
@0xalpharush / @montyly  If you have time, can you help explain how to set up an ast_parsing test to me? I plan to add tests, but could use a little guidance

support abi.encodeCall

---

slither/core/declarations/contract.py
slither/solc_parsing/declarations/contract.py
tests/custom_comments/upgrade.sol
tests/test_features.py

Built on top of https://github.com/crytic/slither/pull/1517
Changes:
- Add tests
- Change the regex for the version naming: `@custom:version name=([\w-]+)` (removing `,`, ` `, and the surrounding `"`) - this is meant to keep the version name simpler
- Change `@custom:security isProxy` to `@custom:security isDelegatecallProxy` - this is meant to prevent future collision with another proxy types (as highlited by [webthethird](https://github.com/crytic/slither/commits?author=webthethird))

Handle custom upgradeability comments for contracts

---

slither/solc_parsing/declarations/function.py
slither/solc_parsing/declarations/modifier.py
slither/utils/expression_manipulations.py
tests/slithir/ternary_expressions.sol
tests/slithir/test_ternary_expressions.py

- support ternaries in gas and value options of call expressions
- handle unused tuple variables
- refactor index access to be like the rest of the conversions
Close #1153, close https://github.com/crytic/slither/issues/1371, close https://github.com/crytic/slither/issues/1198
Replace https://github.com/crytic/slither/pull/1217

Call value ternary

---

slither/tools/upgradeability/__main__.py

Implements #936.
Follows the same approach as the equivalent argument options in the main Slither module, with options to selectively enable/disable checks by name using comma separated lists, and to exclude checks according to impact level.
Does not currently provide an option to enable only a given impact level (i.e., the opposite of `--exclude-<IMPACT>`), but implementing this would be trivial if desired.

Filter upgradeability checks by name/impact

---

slither/tools/upgradeability/checks/variable_initialization.py
slither/tools/upgradeability/checks/variables_order.py

The upgradeability check doesn't consider inherited, private variable declarations nor does it consider immutability. This PR addresses that by using `state_variables_ordered` and checking that variables aren't immutable prior to flagging them.
```
// test.sol 
pragma solidity ^0.8.0;
contract A {
uint private a = 1; // not currently detected 
}
contract B is A {
uint a = 2;
uint immutable b = 3; // fine to delegatecall (same as constant)
}
```
Command: `slither-check-upgradeability test.sol B`
Before:
```
B.a (test.sol#6) is a state variable with an initial value.
B.b (test.sol#7) is a state variable with an initial value.
```
After fix:
```
A.a (test.sol#3) is a state variable with an initial value.
B.a (test.sol#6) is a state variable with an initial value.
```

upgradeability: include inherited private variables, ignore immutables

---

.github/workflows/doctor.yml
setup.py
slither/tools/doctor/__main__.py
slither/tools/doctor/checks/__init__.py
slither/tools/doctor/checks/paths.py
slither/tools/doctor/checks/versions.py

This PR adds a new check to slither-doctor, that validates if `$PATH` is set correctly in the system.
When all looks good, it will print the following:
However, if the path is misconfigured it will print a red message and suggest a folder you should add to `$PATH` (for this example I broke my PATH config on purpose). Users can run slither-doctor as `python3 -m slither.tools.doctor` even if their PATH is misconfigured:
This will also warn if you somehow have another Slither installation earlier in PATH (exemplified here by running slither-doctor from a non-activated venv, while there's a system-wide installation of slither)

slither-doctor: PATH checks

---

slither/slithir/convert.py

This function would benefit from a refactoring. But in-between this adds documentation and clean up the calls to it
Additionally `contract = node.file_scope.get_contract_from_name(t_type.name)` can be changed to `t_type` directly.

Simplify calls to convert_type_of_high_and_internal_level_call

---

slither/core/declarations/contract.py
slither/slithir/convert.py
slither/solc_parsing/declarations/contract.py
slither/solc_parsing/slither_compilation_unit_solc.py
tests/lookup/private_variable.sol
tests/test_features.py

+ improvement documentation for contract.variables

Improve lookup for state variables

---

slither/core/solidity_types/type_alias.py

Adding `type` will help with directly access, like in https://github.com/crytic/slither/blob/7ea572723b4eddb18e716c4ae94e0d2100791127/slither/core/cfg/node.py#L911

Add type to type_alias

---

README.md

Maybe other toolkits don't require `solc` either, I didn't have a chance to find out.

Clarify requirement of installing solc

---

slither/utils/code_complexity.py

File `code_complexity.py` had two bugs in it. This PR fixes both of them.
The first bug was related to strongly connected components algorithm: the final DFS (or `assign` in this case) should be performed on reversed postorder order instead on just postorder.
The second issue concerned calculating cyclomatic complexity: `P` in the formula should be a number of connected components (always `1` in case of solidity functions) instead of strongly connected components.

Bugs fixed in strongly connected components and cyclomatic complexity algorithms

---

slither/detectors/functions/codex.py
slither/slither.py
slither/tools/documentation/__main__.py
slither/utils/codex.py

- Add `--codex-organization` flag
- Add `--include-tests` flag to slither-documentation

Minor codex improvements

---

slither/core/source_mapping/source_mapping.py
slither/detectors/functions/codex.py
slither/printers/summary/constructor_calls.py
slither/tools/flattening/flattening.py
slither/utils/arithmetic.py
slither/utils/standard_libraries.py
tests/arithmetic_usage/test.sol
tests/test_features.py

- Add `Source.content` - the same code was re-use in different parts
- Add `Source.content_hash` to standardize tests on source code
- Add `unchecked_arithemtic_usage`, which returns function with some unchecked arithmetic operations

Minor API improvements

---

slither/core/children/child_expression.py
slither/core/declarations/__init__.py
slither/core/declarations/contract.py
slither/core/declarations/using_for_top_level.py
slither/core/slither_core.py
slither/core/solidity_types/array_type.py
slither/core/solidity_types/function_type.py
slither/core/solidity_types/type_alias.py
slither/core/solidity_types/type_information.py
slither/core/solidity_types/user_defined_type.py
slither/core/variables/__init__.py
slither/slithir/operations/phi_callback.py
slither/slithir/variables/constant.py
slither/slithir/variables/local_variable.py
slither/slithir/variables/reference.py
slither/solc_parsing/declarations/function.py
slither/solc_parsing/solidity_types/type_parsing.py
slither/solc_parsing/variables/variable_declaration.py
slither/visitors/expression/constants_folding.py
slither/visitors/slithir/expression_to_slithir.py

result of trying to reduce mypy/ pyright errors

more types

---

slither/solc_parsing/expressions/expression_parsing.py
slither/solc_parsing/solidity_types/type_parsing.py
tests/src_mapping/ReferencesUserDefinedAliases.sol
tests/src_mapping/ReferencesUserDefinedTypesCasting.sol
tests/test_source_mapping.py

There is a problem with user defined aliases (using `type [...] is [...]` statement) - their `references` list is not updated during parsing.
Also, user defined types (contracts, interfaces, etc.) have missing references when casting (`TypeConversion` expressions).
This PR fixes these issues and is needed to simplify code in #1592.

Missing references fix

---

slither/printers/guidance/echidna.py

Fixes https://github.com/crytic/echidna/issues/918.
This PR makes the echidna printer count enum values as uint256 constants, including them in the `"constants_used"` list so that echidna is aware of them. Currently, when a function has enum arguments, echidna will try all numbers, not privileging in-range enum values over out-of-range values.
Example:
```solidity
contract Example {
bool flag = false;
function setFlag(ExampleEnum a, ExampleEnum b, ExampleEnum c) public {
if (a == ExampleEnum.E28 && b == ExampleEnum.E29 && c == ExampleEnum.E30)
flag = true;
}
function echidna_flag() public view returns (bool) {
return !flag;
}
enum ExampleEnum {
E0,
E1,
// ...
E30
}
}
```
Before this PR, echidna takes a very long time to break the contract (didn't break it in 500000 iterations when I ran …

Add enums to echidna printer's list of constants

---

slither/__main__.py

Since `output_to_sarif` is a function and a "truthy" value, the capturing was enabled despite `outputting_sarif` being false. I've corrected the condition to use `outputting_sarif`

fix stdout capture

---

slither/detectors/shadowing/local.py
tests/detectors/shadowing-local/0.4.25/shadowing_local_variable.sol
tests/detectors/shadowing-local/0.4.25/shadowing_local_variable.sol.0.4.25.LocalShadowing.json
tests/detectors/shadowing-local/0.5.16/shadowing_local_variable.sol
tests/detectors/shadowing-local/0.5.16/shadowing_local_variable.sol.0.5.16.LocalShadowing.json
tests/detectors/shadowing-local/0.6.11/shadowing_local_variable.sol
tests/detectors/shadowing-local/0.6.11/shadowing_local_variable.sol.0.6.11.LocalShadowing.json
tests/detectors/shadowing-local/0.7.6/shadowing_local_variable.sol
tests/detectors/shadowing-local/0.7.6/shadowing_local_variable.sol.0.7.6.LocalShadowing.json

This is an alternative approach to #1404 that modifies the existing `shadowing-local`. Closes https://github.com/crytic/slither/issues/1361

detect local shadowing of return vars

---

slither/detectors/variables/predeclaration_usage_local.py

close https://github.com/crytic/slither/issues/1424

restrict variable-scope detector to only solc 0.4.x

---

slither/slither.py

This function would be helpful to **_de-register_** a detector class from the list of detectors already registered with the slither object.

deregister_detector

---

.github/workflows/features.yml
slither/slithir/operations/high_level_call.py
slither/slithir/operations/new_contract.py
tests/slithir/operation_reads.sol
tests/slithir/test_operation_reads.py

closes https://github.com/crytic/slither/issues/1678
This considers salt in the variables read of `NewContract` and adds testing infra to check the correctness of `vars_read`, `local_vars_read`, `state_vars_read` for nodes and operations.

include salt in NewContract op, add test infra

---

setup.py

follow up on https://github.com/crytic/slither/pull/1743 which accidentally used dev deps instead of required

correct web3 to be required, not dev dep

---

slither/core/declarations/contract.py
slither/solc_parsing/declarations/contract.py
tests/function_features/abstract.sol
tests/function_features/implicit_abstract.sol
tests/slithir/test_ternary_expressions.py
tests/test_features.py

This PR adds an "is_abstract" property to the contract class. Without this class property, detectors can only check for abstractness by verifying all of the functions have implementations.

Abstract contract property

---

slither/visitors/slithir/expression_to_slithir.py
tests/test_ssa_generation.py

https://github.com/crytic/slither/pull/1761 + the latest dev commit

Fix IR operation when initializing array with one-element array literal

---

slither/detectors/attributes/incorrect_solc.py
tests/detectors/solc-version/0.5.16/dynamic_1.sol.0.5.16.IncorrectSolc.json
tests/detectors/solc-version/0.5.16/dynamic_2.sol.0.5.16.IncorrectSolc.json
tests/detectors/solc-version/0.5.16/static.sol.0.5.16.IncorrectSolc.json
tests/detectors/solc-version/0.6.11/dynamic_1.sol.0.6.11.IncorrectSolc.json
tests/detectors/solc-version/0.6.11/dynamic_2.sol.0.6.11.IncorrectSolc.json
tests/detectors/solc-version/0.6.11/static.sol.0.6.11.IncorrectSolc.json
tests/detectors/solc-version/0.7.6/dynamic_1.sol.0.7.6.IncorrectSolc.json
tests/detectors/solc-version/0.7.6/dynamic_2.sol.0.7.6.IncorrectSolc.json
tests/detectors/solc-version/0.7.6/static.sol.0.7.6.IncorrectSolc.json

- Recommend 0.8.18 (0.8.19 being less than 1 month old)
- Remove recommendations for 0.5/0.6/0.7 branches. 0.8 has been around for long enough that everyone should use it.

Update solc version recommendations

---

.github/DISCUSSION_TEMPLATE/installation.yml
.github/DISCUSSION_TEMPLATE/trouble_with_installation.yml
.github/ISSUE_TEMPLATE/false_negative.yml
setup.py

The name must match the category https://github.com/crytic/slither/discussions/categories/installation. Since we made solc-select a dependency via crytic-compile, I also removed that question.

Rename discussion template so it renders

---

CONTRIBUTING.md
tests/e2e/detectors/test_detectors.py

Follow up on https://github.com/crytic/slither/pull/1820 to explain recent changes to testing. Now, zip files will be required to create new detector tests and snapshot txt files will be created and committed instead of json files.

update CONTRIBUTING.md to explain compiling and adding snapshot tests

---

slither/printers/summary/when_not_paused.py

This PR is related to the issue #1671 where when pausable is run then it also shows the constructor/view/pure function. This PR fixes that.

fixed: pausable printer includes checks on constructor()

---

slither/printers/summary/when_not_paused.py

This PR is related to the issue #1670 where it says to change the name of the printer from `pausable` to `not-pausable`

fixed: changed name of the printer pausable -> not-pausable

---

slither/solc_parsing/declarations/contract.py
tests/unit/core/test_contract_declaration.py
tests/unit/core/test_data/contract_declaration/concrete.sol
tests/unit/core/test_data/contract_declaration/concrete_old.sol

Previously was not updating the is_fully_implemented property due to being incorrectly included in the `if` statement.
Fixes #1847

Bug Fix: Contract obj is_fully_implemented

---

slither/detectors/statements/incorrect_strict_equality.py

This commit adds a simple additional check to make sure no strict equality of addresses is flagged at all.

incorrect-equality: do not check addresses

---

slither/tools/read_storage/read_storage.py

In the decode function of ethabi 4.0, there is validate_list_like_param, and the type can only be, isinstance(param, (list, tuple)), so an error will be reported when reading the key of the map.
validate_list_like_param fuction
```
def validate_list_like_param(param: Any, param_name: str) -> None:
if not isinstance(param, (list, tuple)):
raise TypeError(
f"The `{param_name}` value type must be one of list or tuple. "
f"Got {type(param)}"
)
```
```
slot = keccak(encode([key_type, "uint256"], [key, decode("uint256", slot)]))
slot = keccak(encode([key_type, "uint256"], [key, decode(["uint256"], slot)[0]]))
```

fix abi decode

---

slither/detectors/reentrancy/reentrancy_events.py

improve reentrancy events documentation

---

slither/slithir/operations/binary.py

Closes https://github.com/crytic/slither/issues/1687

remove modulo binop from `can_be_checked_for_overflow`

---

examples/flat/a.sol
examples/flat/b.sol
scripts/ci_test_flat.sh
slither/core/compilation_unit.py
slither/core/declarations/solidity_variables.py
slither/tools/flattening/export/export.py
slither/tools/flattening/flattening.py

fix #1410 #1837 
- Fix the type hint for custom errors in `SlitherCompilationUnit` where they are `CustomErrorTopLevel` and not just `CustomError`
- Expose the custom error in `SolidityCustomRevert` so when analyzing a revert SOLIDITY_CALL in slithir it's possible to get the custom error used
- Set the logging level to INFO for the flattening tool otherwise the logs are not showed
- Changed `list_top_level` and `list_contracts` to be a set and not a list. This avoid duplicates and a necessay check before appending that the element is not present as this is error prone. For example at the moment this check is missing when adding a top level function so if you were to use a top level function n times you will get n definitions of that function in the flattened output

make slither-flat work for top level errors, structs, enums

---

slither/solc_parsing/declarations/function.py

Fix #1867 for compact AST.
When applying the same fix to the legacy AST case strange things start happening and i'm not sure it's worth to try to fix it since it's discontinued.
```solidity
contract T {
function a() public {
if (2>1){
(uint aa, uint bb) = b();
uint tot = aa+bb;
}
if (2<1){
(uint aa, uint bb) = b();
uint tot2 = aa+bb;
}
}
function b() internal returns(uint,uint) {return(2,3); }
}
```
Before
```
...
Expression: 2 < 1
IRs:
TMP_2(bool) = 2 < 1
CONDITION TMP_2
Expression: (aa,bb) = b()
IRs:
TUPLE_1(uint256,uint256) = INTERNAL_CALL, T.b()()
aa(uint256)= UNPACK TUPLE_1 index: 0 
bb(uint256)= UNPACK TUPLE_1 index: 1 
Expression: tot2 = aa_scope_0 + bb_scope_1
IRs:
TMP_3(uint256) = aa_scope_0 + bb_scope_1
tot2(uint256) := TMP_3(uint256)
```
After
```
...
Expression: 2 < 1
IRs: …
```

FIx return variables shadowing compact AST

---

setup.py

Right now, these dependencies are include in web3py and we should explicit declare them in case something changes upstream

make transitive dependencies explicit

---

.github/workflows/ci.yml
scripts/ci_test_interface.sh
setup.py
slither/tools/interface/__main__.py
tests/tools/interface/ContractMock.sol
tests/tools/interface/test_1.sol
tests/tools/interface/test_2.sol
tests/tools/interface/test_3.sol
tests/tools/interface/test_4.sol
tests/tools/interface/test_5.sol
tests/tools/interface/test_6.sol
tests/tools/interface/test_7.sol

As per issue #1893 
This tool outputs an interface file for a given contract input. The input can be a local source file or a deployment address if the contract is verified on etherscan.
Usage:
`slither-interface <ContractName> <Source File or Address>`
For example:
`slither-interface WETH9 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2`
will output the interface file IWETH9.sol in crytic-export/interfaces.
There are optional flags for unrolling structs or excluding structs/enums/errors/events.
Tests can be found in `scripts/ci_test_interface.sh`
I believe I did testing/linting correctly, let me know if I need to fix anything.

add tool slither-interface

---

slither/solc_parsing/slither_compilation_unit_solc.py

partial fix of #1853
Opened PR per request in #1854
AssertionError with stack trace can occur while parsing contracts that provides no context to what was parsed that threw the error as described in #1853. This change catches this error, logs additional context, and then throws the error again.
An example of the logging from code I am working on:
```
$ slither .
...
Compiler run successful
ERROR:SlitherSolcParsing:
Failed to parse MyERC20Controller.constructor (contracts/MyERC20Controller.sol#19-25):
(tokenX,tokenY) = IMyFactoryCallback(msg.sender).tokens()
(success,data) = msg.sender.delegatecall(abi.encodeWithSelector(IMyFactoryCallback.newTokens.selector,tokenX,tokenY))
require(bool,string)(success,Factory new tokens failed)
_tokens = abi.decode(data,(IMyERC20[6]))
Traceback (most …
```

Catch AssertionError and log context and raise again while parsing

---

slither/analyses/evm/convert.py

In `generate_source_to_evm_ins_mapping`, the statement `offset, _length, file_id, _ = mapping_item` for unpacking the source mapping items will not work in new solidity versions. Because the generated source mapping items are in the format `s:l:f:j:m` since solidity v0.6.0, the new field `m` has been added. See more here [source-mappings](https://docs.soliditylang.org/en/v0.6.0/miscellaneous.html#source-mappings)

fix generate_source_to_evm_ins_mapping

---

slither/slithir/convert.py

Fix https://github.com/crytic/slither/issues/1918

fix: make _convert_to_structure_to_list return a type instead of an ElementaryType's `type` field

---

slither/slithir/convert.py

Popping from `bytes` should give a `bytes1` type not `bytes` https://github.com/crytic/slither/issues/1904#issuecomment-1552251332

Fix bytes pop ir

---

tests/e2e/solc_parsing/test_ast_parsing.py
tests/e2e/solc_parsing/test_data/expected/yul-top-level-0.8.0.sol-0.8.0-compact.json

There was a missing artifact and the test was x-failing instead of failing

fail if artifact does not exist

---

slither/detectors/variables/similar_variables.py

Fixes #1630
Optimizations to the algorithm for detecting similar variable names in similar_variables.py. 
Runtime for slither/dev on current C4 competiton MAIA codebase:
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
40      0.005    0.000    39.760   0.994   .../slither/detectors/variables/similar_variables.py:76(_detect)
Runtime for optimized version on same codebase:
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
40      0.004    0.000    17.769   0.444   .../slither/detectors/variables/similar_variables.py:83(_detect)
Runtime is reduced by >50% here, and the issues detected are identical.
Changes (in `detect_sim`):
- Inner loop reworked so that it doesn't repeat comparisons. No need to compare the current outer loop's variable to anything …

Optimizations for similar_variables.py

---

slither/solc_parsing/slither_compilation_unit_solc.py
tests/unit/core/test_data/inheritance_resolution_error/contract_with_duplicate_names.sol
tests/unit/core/test_data/inheritance_resolution_error/import.sol
tests/unit/core/test_error_messages.py

Add a fix suggestion for cases like https://github.com/crytic/slither/issues/1758 and prevent infinite loop

inform user if inheritance cannot be resolved

---

slither/detectors/variables/similar_variables.py

Issue #1630 
Adding in the additional optimizations for the similar variable name detector as described in https://github.com/crytic/slither/pull/1945#issuecomment-1575060352 
Changes:
- length check brought out of `similar` into `detect_sim`. If the lengths aren't the same, no need to run `v2.name.lower()`
- `v1.name.lower()` and `v2.name.lower()` are cached in `detect_sim` and given as inputs for `similar` so that .lower() doesn't have to be run an extra 2 times in the `SequenceMatcher` call.
Again running on the C4 contest Maia codebase:
Current slither/dev:
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
40      0.004    0.000    17.769   0.444   .../slither/detectors/variables/similar_variables.py:83(_detect)
With new optimizations:
ncalls  tottime  percall …

Additional optimizations for similar_variables.py

---

.github/workflows/ci.yml
.github/workflows/test.yml
slither/utils/loc.py

This fixes the following error:
ValueError: mutable default <class 'slither.utils.loc.LoCInfo'> for field src is not allowed: use default_factory

Fix execution in Python 3.11

---

CITATION.cff
README.md

Fix the status badges and include a link to the documentation page that is now generated
Edit:
Additional changes include a direct link to the wiki
updated slack badge to join
more information in the citation.cff file
slight style changes regarding the markup of the header

docs(readme): add new docs link

---

.github/workflows/linter.yml
.github/workflows/matchers/pylint.json
.github/workflows/matchers/yamllint.json
.github/workflows/pylint.yml

Add problem matchers for pylint and yamllint. This will show a diagnostic using github checks API like:

ci: add problem matchers for yamllint and pylint

---

tests/unit/slithir/test_ternary_expressions.py

closes https://github.com/crytic/slither/issues/2032

fix ternary rewrite test and make assertion more strict

---

slither/core/expressions/unary_operation.py

Small bugfix for UnaryOperation. Until now in code like this:
```solidity
function some_view() view returns (int) {
return -someParameter;
}
```
Slither believes that `someParameter` is an lvalue. One of the results is that `slither.visitors.expression.write_var` believes that `someParameter` is written to.
I'm happy to add some test if needed.

UnaryOperation: -variable and +variable doesn't make variable an lvalue

---

slither/core/declarations/contract.py

The function should compare v.canonical_name with the parameter. Currently, it works the same as get_state_variable_from_name()

fix typo in Contract.get_state_variable_from_canonical_name()

---

slither/detectors/statements/divide_before_multiply.py

Fix divide before multiply detector non deterministic results

---

slither/slithir/convert.py
slither/slithir/operations/init_array.py
slither/slithir/operations/new_array.py
tests/unit/slithir/test_ssa_generation.py

fix(convert): do not convert array type to elementary for `InitArray`

---

slither/printers/guidance/echidna.py

Fix https://github.com/crytic/slither/issues/2104
On
```solidity
contract A{
revert();
assert(false);
}
function g() public{
assert(true);
revert();
assert(false);
}
function h() public{
if(true) assert(false); else assert(true);
}
}
```
The printer will now output 
```
"f()": [
{
"start": 49,
"length": 13,
"filename_relative": "assert.sol",
"filename_absolute": "/private/tmp/assert.sol",
"filename_short": "assert.sol",
"is_dependency": false,
"lines": [
5
],
"starting_column": 3,
"ending_column": 16
}
],
"g()": [
{
"start": 92,
"length": 12,
"filename_relative": "assert.sol",
"filename_absolute": "/private/tmp/assert.sol",
"filename_short": "assert.sol",
"is_dependency": false,
"lines": [
9
],
"starting_column": 3,
"ending_column": 15
},
{
"start": 120,
"length": 13, …
```

Add detailed assert info for echidna

---

slither/core/variables/variable.py
tests/e2e/compilation/test_data/test_contract_data/test_contract_data.sol
tests/e2e/compilation/test_resolution.py

Hello!
This is my attempt at addressing #2127  with 1 test added.
Thanks!

Allow function parameter name to be empty when casting to string

---

slither/solc_parsing/solidity_types/type_parsing.py

Fix #2117.
```
pragma solidity 0.8.19;
interface Interface {
struct ZZZ {
int x;
int y;
}
enum QQQ {
A,
B
}
}
struct ZZZ {
int x;
int y;
int z;
}
enum QQQ {
A,
B
}
contract A {
function test(ZZZ memory zzz, QQQ qqq) external {
zzz.z = 3;
Interface.QQQ qqq2 = Interface.QQQ.A;
Interface.ZZZ memory zzz2 = Interface.ZZZ(1,2);
}
}
```
ir
```
Contract A
Function A.test(ZZZ,QQQ) (*)
Expression: zzz.z = 3
IRs:
REF_0(int256) -> zzz.z
REF_0(int256) (->zzz) := 3(int256)
Expression: qqq2 = Interface.QQQ.A
IRs:
REF_1(None) -> Interface.QQQ
REF_2(None) -> REF_1.A
qqq2(Interface.QQQ) := REF_2(None)
Expression: zzz2 = Interface.ZZZ(1,2)
IRs:
TMP_0(Interface.ZZZ) = new ZZZ(1,2)
zzz2(Interface.ZZZ) := TMP_0(Interface.ZZZ)
```

Prioritize checking canonical_name for type inference

---

slither/core/dominators/utils.py
slither/vyper_parsing/declarations/function.py

Updates Vyper support to include the same notion of reachability for nodes in the CFG as was introduced for solc in https://github.com/crytic/slither/pull/1984
closes https://github.com/crytic/slither/issues/2171

update vyper cfg to include reachability

---

slither/tools/read_storage/__main__.py

Before:
```bash
$ slither-read-storage 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 --contract-name WETH8 # woops! did you mean WETH9?
$ # silently fails
```
After
```bash
$ slither-read-storage 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 --contract-name WETH8
Traceback (most recent call last):
File "/Users/usmannkhan/Development/slither/env/bin/slither-read-storage", line 8, in <module>
sys.exit(main())
File "/Users/usmannkhan/Development/slither/slither/tools/read_storage/__main__.py", line 134, in main
raise SlitherError(f"Contract {args.contract_name} not found.")
slither.exceptions.SlitherError: Contract WETH8 not found.
```

Raise an error when a missing contract is specified to read-storage

---

slither/core/declarations/function.py
tests/unit/core/test_function_declaration.py

`is_reentrant`  was returning True for internal functions even if all entry points had the nonreentrant decorator, causing FPs on examples like:
```
balances: HashMap[address, uint256]
@external
@nonreentrant("lock")
def withdraw_locked():
self.withdraw()
@internal
def withdraw():
raw_call(msg.sender, b"", value= self.balances[msg.sender])
self.balances[msg.sender] = 0
```

fix is_reentrant for internal vyper functions

---

slither/detectors/variables/predeclaration_usage_local.py

Replaced the character `z` with `x` in the pre-declaration section of the detector documentation under the `Pre-declaration Usage of Local Variables` segment.
fixes: #2245

Substituted the letter `z` with `x` in pre-declaration

---

slither/detectors/statements/divide_before_multiply.py

divide-before-multiply: Detect also in modifiers

---

README.md
slither/detectors/assembly/incorrect_return.py
slither/detectors/assembly/return_instead_of_leave.py
tests/e2e/compilation/test_resolution.py

Small PR to fix detector links that didn't work

fix: broken doc links

---

slither/utils/myprettytable.py

slither: utils: respect colorization state when printing tables

---

slither/__main__.py
slither/slither.py
slither/utils/command_line.py

This makes the triage database file customizable. By default it will continue being `slither.db.json` but the user can now point to a different file or a file in another directory.

Make triage database path customizable

---

slither/core/compilation_unit.py
slither/core/declarations/contract.py
slither/core/variables/variable.py
slither/detectors/variables/unchanged_state_variables.py
slither/printers/summary/variable_order.py
slither/tools/read_storage/read_storage.py
slither/tools/upgradeability/checks/variable_initialization.py
slither/tools/upgradeability/checks/variables_order.py
slither/utils/encoding.py
slither/utils/upgradeability.py

The following changes were added to address #1644: 
- `Contract.stored_state_variables`: Filters and returns state variables with storage, excluding constant or immutable ones. 
- `Contract.stored_state_variables_ordered`: Returns stored state variables in their declaration order, filtering out constants or immutables.
- `Variable.is_stored`: Determines if a variable is stored, based on it not being constant or immutable, ready for future updates.
- Updated code to use the new methods

Create a variable API that filters out constants and immutables

---

slither/solc_parsing/slither_compilation_unit_solc.py
tests/unit/core/test_data/inheritance_with_renaming/a.sol
tests/unit/core/test_data/inheritance_with_renaming/b.sol
tests/unit/core/test_data/inheritance_with_renaming/c.sol
tests/unit/core/test_inheritance.py

Builds off https://github.com/crytic/slither/pull/2306 and also add support for renaming in base constructor calls like:
```
import {B as Base} from "./b.sol";
contract A is Base(address(0)) {
constructor (address x) {}
}
```
Refactored the duplicated remapping and renaming code into a helper function

fix: support renaming in base inheritance and base constructor calls

---

slither/__main__.py
slither/core/slither_core.py
slither/slither.py
slither/utils/command_line.py

Add --include-paths option

---

slither/printers/abstract_printer.py
slither/printers/inheritance/inheritance_graph.py
tests/e2e/printers/test_data/test_contract_names/A.sol
tests/e2e/printers/test_data/test_contract_names/B.sol
tests/e2e/printers/test_data/test_contract_names/B2.sol
tests/e2e/printers/test_data/test_contract_names/C.sol
tests/e2e/printers/test_printers.py

Hello!
This is my attempt at addressing #2107 with 1 test added. 
The updated inheritance graph printer generates the following graph for the example provided in the issue:
The call graph printer already uses contract id to handle multiple contracts with same names: 
Thanks!

Update inheritance graph printer to handle multiple contracts with same names 

---

slither/tools/mutator/__main__.py
slither/tools/mutator/mutators/abstract_mutator.py
slither/tools/mutator/utils/file_handling.py
slither/tools/mutator/utils/testing_generated_mutant.py

This PR provides several bugfixes on top of #2302:
- If to files were backuped / mutated with the same name (e.g. `path/Token.sol` and `path2/Token.sol`).
- If the mutation directory was not set to  `mutation_campaign`, the mutants were not written in the appropriate directory
- If the `contracts-name` parameter was used, contracts were not properly filtered
- Contracts could be mutated more than once
On the quality side, it also try to replace most of the `os` module usage with `Pathlib` for additional clarity.

slither-mutate: bugfix when two files have the same name

---

slither/core/declarations/solidity_variables.py
slither/vyper_parsing/expressions/expression_parsing.py
tests/e2e/vyper_parsing/snapshots/ast_parsing__vyper_cfgir_builtins_c__0.txt
tests/e2e/vyper_parsing/snapshots/ast_parsing__vyper_cfgir_builtins_test_builtins__0.txt
tests/e2e/vyper_parsing/test_data/builtins.vy

closes https://github.com/crytic/slither/issues/2190

add support for send builtin

---

slither/core/declarations/function.py
slither/solc_parsing/declarations/function.py

Add virtual and override attribute in Function

---

slither/solc_parsing/declarations/function.py
slither/visitors/slithir/expression_to_slithir.py
tests/unit/core/test_data/tuple_assign/test_tuple_assign.sol
tests/unit/core/test_tuple_assign.py

This fixes [issue 1913](https://github.com/crytic/slither/issues/1913).
Previously, when performing an assignment whose variables were originally declared in a tuple-based declaration, the projection components were reused:
```
function test() external returns(int) {
(int a, int b, int c) = threeRet(3);
(a, c) = twoRet(b);
return b;
}
...
Expression: (a,c) = twoRet(b)
IRs:
TUPLE_1(int256,int256) = INTERNAL_CALL, Test.twoRet(int256)(b)
a(int256)= UNPACK TUPLE_1 index: 0 
c(int256)= UNPACK TUPLE_1 index: 2 
```
This happened because of some code in the `_post_assignment_operation` function in `expression_to_slithir.py`:
```
if (
isinstance(left[idx], LocalVariableInitFromTuple)
and left[idx].tuple_index is not None
):
index = left[idx].tuple_index
```
We shouldn't be reusing the variable's …

fix: preserve empty tuple components during declaration-to-assignment conversion

---

slither/visitors/slithir/expression_to_slithir.py
tests/e2e/solc_parsing/test_data/type-aliases.sol

closes https://github.com/crytic/slither/issues/2122

fix: lookup of type alias as member of contract

---

slither/detectors/slither/name_reused.py

Set `name-reused` detector to only run on Truffle projects 
closes #2390

Filter name-reused detector to only run on Truffle projects (#2390)

---

slither/__main__.py
tests/e2e/test_cli.py

Following #2011
When trying to analyze a bogus Solidity file, `slither` output is a bit crowded with multiple stacktraces of exception thrown (as shown in the previous issue).
If the compilation fails in Crytic with an `InvalidCompilation` exception, we don't print the backtrace and instead exit with a new error code (`2`).
The new output will be like this:
```shell
➜ slither Test.sol             
'solc --version' running
'solc Test.sol --combined-json abi,ast,bin,bin-runtime,srcmap,srcmap-runtime,userdoc,devdoc,hashes,compact-format --allow-paths .,./slither' running
Compilation warnings/errors on Test.sol:
Test.sol:2:1: Error: Source file requires different compiler version (current compiler is 0.5.1+commit.c8a2cb62.Darwin.appleclang - note that nightly builds are considered to be …
```

Reduce verbosity for InvalidCompilation errors

---

slither/solc_parsing/expressions/find_variable.py
tests/unit/core/test_data/scope_with_renaming/core/MainContract.sol
tests/unit/core/test_data/scope_with_renaming/core/ParentContract.sol
tests/unit/core/test_data/scope_with_renaming/errors/MainErrors.sol
tests/unit/core/test_data/scope_with_renaming/errors/ParentContractErrors.sol
tests/unit/core/test_scope_with_renaming.py
tests/unit/core/test_using_for.py

closes https://github.com/crytic/slither/issues/2454
replaces https://github.com/crytic/slither/pull/2455
The scope for `FunctionContract` was using the inherited contract's scope and not the declarer's so it was find the wrong alias

fix: use contract declarer's scope for name resolution

---

slither/analyses/evm/convert.py
slither/printers/summary/evm.py

Fixes bug in the EVM printer :
When trying to merge the previous mapping to the new one in the `source-mappings`, if the previous field was one of the non integer fields, it would crash with a `ValueError`.
Trying to print a contract that inherits from another file would not accurately pick the source file from the declarer contract but the current contract.

Fix bugs in the EVM printer

---

.gitignore
slither/core/slither_core.py

Currently in the process of doing a very large code audit using the `triage-mode` and due to being such a large codebase we really need the db file saved on each step to help in the process of cancelling and restarting the slither test tool after code edits and not losing all pasted saved `save_results_to_hide` that are just kept in memory. 
Anyway was a very simple fix and now the db is saved each time `save_results_to_hide` is called. 
Pretty sure this will be helpful for others doing large audits too. 
Thanks

Write `slither.db.json` file on each save_results_to_hide

---

slither/core/source_mapping/source_mapping.py
tests/e2e/compilation/test_data/test_change/README.md
tests/e2e/compilation/test_data/test_change/foundry.toml
tests/e2e/compilation/test_data/test_change/src/Counter.sol
tests/e2e/compilation/test_diagnostic.py

Fixes https://github.com/crytic/slither/issues/2328
The new error message is a bit more explicit than the previous one.
However, I was unsure on what Exception to throw there: I opted for the `SlitherException` but it yields to some clutter in the error log because it prints the backtrace.
```shell
➜ slither --ignore-compile tests/e2e/compilation/test_data/test_change/
--ignore-compile used, if something goes wrong, consider removing the ignore compile flag
Traceback (most recent call last):
File "/Users/dm/Projects/slither/slither/__main__.py", line 859, in main_impl
) = process_all(filename, args, detector_classes, printer_classes)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dm/Projects/slither/slither/__main__.py", line 107, in process_all
) = …
```

Improve message error for when Crytic throws a KeyError.

---

scripts/ci_test_upgradability.sh
slither/tools/upgradeability/checks/all_checks.py
slither/tools/upgradeability/checks/initialization.py
tests/tools/check_upgradeability/contract_initialization.sol
tests/tools/check_upgradeability/test_10.txt
tests/tools/check_upgradeability/test_11.txt
tests/tools/check_upgradeability/test_12.txt
tests/tools/check_upgradeability/test_13.txt
tests/tools/check_upgradeability/test_14.txt
tests/tools/check_upgradeability/test_15.txt
tests/tools/check_upgradeability/test_2.txt
tests/tools/check_upgradeability/test_3.txt
tests/tools/check_upgradeability/test_4.txt
tests/tools/check_upgradeability/test_5.txt
tests/tools/check_upgradeability/test_6.txt
tests/tools/check_upgradeability/test_7.txt
tests/tools/check_upgradeability/test_8.txt
tests/tools/check_upgradeability/test_9.txt

When upgrading a proxy's implementation with [reinitializer](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/utils/Initializable.sol#L152), developers could errorly write multiple new reinitializers. If the new reinitializer with a higher version is called first, the reinitializer with a lower version can't be called later (you can't call a reinitializer with a lower version) and may leave uninitalized state variables.
This could lead to severe results in the real world. For example, the Ronin Network prepared two upgrades for their gateway contract and wrote two reinitializers (`initializeV3()` and `initializeV4()`). However, the developer calls the `initializeV4()` first and leaves the state variables `_operatorWeight` and `_totalOperatorWeight` …

tool: add detector for multiple new reinitializers

---

slither/slithir/operations/member.py

Fix for #2566 which adds Event as a valid left variable

bugfix: IR generation when parsing Event as left variable

---

slither/core/variables/state_variable.py
slither/solc_parsing/variables/state_variable.py

Add the location to a `StateVariable` so we know if it's in persistent or transient storage.

Add StateVariable location

---

slither/core/compilation_unit.py
slither/core/declarations/contract.py
slither/core/variables/state_variable.py
slither/core/variables/variable.py
slither/detectors/variables/unchanged_state_variables.py
slither/printers/summary/variable_order.py
slither/solc_parsing/declarations/contract.py
slither/tools/upgradeability/checks/variable_initialization.py
slither/tools/upgradeability/checks/variables_order.py
slither/utils/upgradeability.py
slither/vyper_parsing/declarations/contract.py

This PR does the following:
- Compute the storage layout for both transient and storage
- API changes in the Contract class
- `state_variables_ordered`: All state variables including constants and immutables. Same as before
- `storage_variables_ordered`: Only state variables with storage location
- `transient_variables_ordered`: Only state variables with transient location
- Removed the unordered storage version called `stored_state_variables` as it adds complexity to the API, it's enough the ordered version independently if the order matters or not,
-  Moved the `is_stored` property to the `StateVariable` class from the `Variable` class as it only makes sense for `StateVariable`, all the code was already using it after checking if the var is a `StateVariable`. Added the `is_transient` …

Improve transient storage support

---

slither/slithir/convert.py
tests/unit/slithir/test_argument_reorder.py
tests/unit/slithir/test_data/argument_reorder/test_overridden_function.sol

Fix reorder arguments when a function is overridden with diff param names

---

slither/tools/mutator/__main__.py
slither/tools/mutator/mutators/abstract_mutator.py
slither/tools/mutator/utils/testing_generated_mutant.py

Mutation campaigns take a long time, it's a bummer if we get an hour into it and then realize we're mutating the wrong set of files. We used to log a list of ignored files, but that gives us incomplete info. With this change, we instead log the list of files that are going to be mutated (ie walk the given `codebase` and remove anything in the `paths_to_ignore_list`)

Updated slither-mutate logs

---

slither/analyses/write/are_variables_written.py

When a return variable is named it could appear only in the RETURN node hence we should also consider the variables there

Fix are_variables_written analysis for named return variables

---

slither/tools/documentation/README.md

Changed "documenation" to "documentation" for accurate spelling.

Typo fix  README.md

---

slither/tools/read_storage/read_storage.py

Fix a crash when a struct has only other structs. The `size` variable would not be initialized.
```solidity
contract T {
struct A {
uint256 value;
}
struct T {
A _inner;
}
T _t;
}
```
```
File ".../slither/tools/read_storage/read_storage.py", line 597, in _find_struct_var_slot
return info, type_to, slot_as_bytes, size, offset
^^^^
UnboundLocalError: cannot access local variable 'size' where it is not associated with a value
```

Fix slither-read-storage crash when a structure has only other structs as fields

---

slither/tools/mutator/__main__.py
slither/tools/mutator/mutators/LIR.py

Small improvement to slither-mutate by checking if a contract is an interface properly and not relying on naming convention

slither-mutate: Check if a contract is an interface properly

---

slither/core/cfg/node.py
slither/core/declarations/function.py
slither/slithir/variables/local_variable.py
tests/e2e/detectors/snapshots/detectors__detector_ReentrancyEth_0_4_25_DAO_sol__0.txt
tests/unit/slithir/test_data/variable_read_write_storage_pointer/local_alias.sol
tests/unit/slithir/test_data/variable_read_write_storage_pointer/with_library.sol
tests/unit/slithir/test_data/variable_read_write_storage_pointer/without_library.sol
tests/unit/slithir/test_storage_pointer.py

- Add support for storage pointer info through phi (storage parameter)
- Update read/write analysis to be more robust with storage parameter

Improve support for storage pointer analysis

---

slither/detectors/statements/calls_in_loop.py
slither/detectors/statements/costly_operations_in_loop.py
slither/detectors/statements/delegatecall_in_loop.py
slither/detectors/statements/msg_value_in_loop.py
tests/e2e/detectors/snapshots/detectors__detector_CostlyOperationsInLoop_0_4_25_multiple_costly_operations_in_loop_sol__0.txt
tests/e2e/detectors/snapshots/detectors__detector_CostlyOperationsInLoop_0_5_16_multiple_costly_operations_in_loop_sol__0.txt
tests/e2e/detectors/snapshots/detectors__detector_CostlyOperationsInLoop_0_6_11_multiple_costly_operations_in_loop_sol__0.txt
tests/e2e/detectors/snapshots/detectors__detector_CostlyOperationsInLoop_0_7_6_multiple_costly_operations_in_loop_sol__0.txt
tests/e2e/detectors/snapshots/detectors__detector_DelegatecallInLoop_0_4_25_delegatecall_loop_sol__0.txt
tests/e2e/detectors/snapshots/detectors__detector_DelegatecallInLoop_0_5_16_delegatecall_loop_sol__0.txt
tests/e2e/detectors/snapshots/detectors__detector_DelegatecallInLoop_0_6_11_delegatecall_loop_sol__0.txt
tests/e2e/detectors/snapshots/detectors__detector_DelegatecallInLoop_0_7_6_delegatecall_loop_sol__0.txt
tests/e2e/detectors/snapshots/detectors__detector_DelegatecallInLoop_0_8_0_delegatecall_loop_sol__0.txt
tests/e2e/detectors/snapshots/detectors__detector_MsgValueInLoop_0_4_25_msg_value_loop_sol__0.txt
tests/e2e/detectors/snapshots/detectors__detector_MsgValueInLoop_0_5_16_msg_value_loop_sol__0.txt
tests/e2e/detectors/snapshots/detectors__detector_MsgValueInLoop_0_6_11_msg_value_loop_sol__0.txt
tests/e2e/detectors/snapshots/detectors__detector_MsgValueInLoop_0_7_6_msg_value_loop_sol__0.txt
tests/e2e/detectors/snapshots/detectors__detector_MsgValueInLoop_0_8_0_msg_value_loop_sol__0.txt
tests/e2e/detectors/snapshots/detectors__detector_MultipleCallsInLoop_0_4_25_multiple_calls_in_loop_sol__0.txt
tests/e2e/detectors/snapshots/detectors__detector_MultipleCallsInLoop_0_5_16_multiple_calls_in_loop_sol__0.txt
tests/e2e/detectors/snapshots/detectors__detector_MultipleCallsInLoop_0_6_11_multiple_calls_in_loop_sol__0.txt
tests/e2e/detectors/snapshots/detectors__detector_MultipleCallsInLoop_0_7_6_multiple_calls_in_loop_sol__0.txt

Fix #1468 by adding a function calls stack in the output so it should be easier to understand

Add calls stack information to detectors

---

docs/src/Usage.md

The description mention `SafeMath`, not `Migrations`.

Fix Usage.md
