scripts/travis_test.sh, slither/__main__.py, slither/detectors/statements/assembly.py, tests/inline_assembly_contract.sol, tests/inline_assembly_library.sol
Detect functions using inline assembly.
Refs: https://github.com/trailofbits/slither/issues/26
=> detectors: Add assembly detector.

README.md, scripts/travis_test.sh, slither/__main__.py, slither/detectors/operations/low_level_calls.py, tests/low_level_calls.sol
Closes https://github.com/trailofbits/slither/issues/27
=> detectors: Add low level calls detector.

README.md, scripts/travis_test.sh, slither/__main__.py, slither/detectors/variables/possible_const_state_variables.py, tests/const_state_variables.sol
Closes https://github.com/trailofbits/slither/issues/25
=> detectors: Add state variables that could be const detector.

examples/scripts/functions_called.py
Two small print typos in the functions_called.py script
=> small typos in print statement

slither/printers/functions/authorization.py
=> fix vars-and-auth print bug

slither/solc_parsing/declarations/contract.py, slither/solc_parsing/expressions/expression_parsing.py, slither/solc_parsing/slitherSolc.py
- Follow truffle id remapping
- Add support for library name remapping
=> Improve support for truffle and complex project architecture

.travis.yml, scripts/travis_test_cli.sh, scripts/travis_test_printers.sh, scripts/travis_test_slither_config.sh, slither/__main__.py, tests/config/slither.config.json
=> Re-add --solc-ast

slither/core/slither_core.py, slither/slither.py, slither/solc_parsing/slitherSolc.py
This pull request aims to resolve #218 .
All relevant information regarding this PR is described in the issue.
=> Fix for regression in line/column number calculations

README.md, slither/detectors/abstract_detector.py, slither/detectors/functions/external_function.py, slither/detectors/variables/possible_const_state_variables.py, tests/expected_json/const_state_variables.constable-states.json, tests/expected_json/external_function.external-function.json
And apply it to the detectors constable-states and external-function.
This closes #176.
=> Add 'optimization' as a new detector category

slither/__main__.py
Adds a --exclude-optimization flag to exclude optimization analyses.
=> Add --exclude-optimization flag

CONTRIBUTING.md, slither/utils/standard_libraries.py, utils/demo/README.md, utils/demo/__main__.py
Detection for Aragon OS and [Aragon App](https://github.com/aragon/aragonOS/blob/dev/contracts/apps/AragonApp.sol).
=> Detect Aragon OS

scripts/tests_generate_expected_json_4.sh, scripts/travis_test_etherscan.sh, slither/core/cfg/node.py, slither/core/declarations/function.py, slither/detectors/variables/possible_const_state_variables.py, slither/printers/summary/slithir.py, slither/slithir/convert.py, slither/slithir/tmp_operations/tmp_call.py, slither/solc_parsing/declarations/contract.py, slither/solc_parsing/declarations/function.py, slither/solc_parsing/slitherSolc.py, tests/expected_json/deprecated_calls.deprecated-standards.json, tests/expected_json/deprecated_calls.deprecated-standards.txt, utils/similarity/encode.py
This PR aims to translate to SlithIR the Solidity expressions that are not yet converted, including:
- Modifier calls
- State variable initialization
This PR will need extensive tests prior to being merged
=> Translate to SlithIR missing expressions

slither/detectors/naming_convention/naming_convention.py, slither/solc_parsing/declarations/function.py
=> Naming convention: allow underscore for private/internal function

scripts/tests_generate_expected_json_5.sh, slither/core/expressions/literal.py, slither/detectors/statements/too_many_digits.py, slither/slithir/variables/constant.py, slither/solc_parsing/expressions/expression_parsing.py, slither/utils/arithmetic.py, slither/visitors/slithir/expression_to_slithir.py, tests/expected_json/too_many_digits.too-many-digits.json, tests/expected_json/too_many_digits.too-many-digits.txt, tests/too_many_digits.sol
Keep the type sub denomination info until the IR conversion to improve the too many digit detector
Fix #297
As this PR impacts the parsing, it needs intensive testing before being merged
=> Late subdenomination conversion

slither/slithir/operations/send.py, slither/slithir/operations/transfer.py
Fix bug introduced in https://github.com/crytic/slither/pull/311
=> Fix reentrancy detector

slither/printers/summary/human_summary.py, slither/slither.py
Adds the number of issues that have the impact level Optimization to the human summary printer
=> Add optimization impact level to human summary

slither/core/declarations/function.py, slither/core/variables/state_variable.py, slither/core/variables/variable.py, slither/printers/all_printers.py, slither/printers/guidance/echidna.py, slither/printers/summary/function_ids.py, slither/solc_parsing/declarations/contract.py
Fix https://github.com/crytic/slither/issues/319
Features:
- Detect payable functions
- Detect functions using assert/block.number/msg.sender/timestamp/msg.gas
- Constant extraction (including binary type used)
Example of output:
```solidity
contract C{
uint public a = 10;
string st = "this_is_a_test";
modifier after_block{
require(block.number > 10000);
_;
} 
uint l;
require(l == 20);
}
function g() after_block public{
}
function h() payable external{
} 
function i() public{
assert(a * 5 >= 100);
}
}
```
```json
{
"payable": {
"C": [
"h()"
]
},
"timestamp": {},
"block_number": {
"C": [
"g()"
]
},
"msg_sender": {},
"msg_gas": {},
"assert": {
"C": [
"i()"
]
},
"constant_functions": {
"C": [
"a()"
]
},
"constants_used": {
"C": {
"f()": [
20
],
"g()": [
10000
],
"i()": [ …
```
=> Echidna guidance printer 

slither/__main__.py, slither/printers/abstract_printer.py, slither/printers/call/call_graph.py, slither/printers/functions/authorization.py, slither/printers/functions/cfg.py, slither/printers/guidance/echidna.py, slither/printers/inheritance/inheritance.py, slither/printers/inheritance/inheritance_graph.py, slither/printers/summary/constructor_calls.py, slither/printers/summary/contract.py, slither/printers/summary/data_depenency.py, slither/printers/summary/function.py, slither/printers/summary/function_ids.py, slither/printers/summary/human_summary.py, slither/printers/summary/modifier_calls.py, slither/printers/summary/require_calls.py, slither/printers/summary/slithir.py, slither/printers/summary/slithir_ssa.py, slither/printers/summary/variable_order.py, slither/utils/command_line.py, slither/utils/json_utils.py
This PR creates a JSON output for the printers.
Three printers don't have a json format for now (slithir, slithir-ssa, and constructor)
The PR is based on https://github.com/crytic/slither/pull/355
=> Create Json output for printers

.travis.yml, scripts/travis_test_kspec.sh, setup.py, slither/tools/kspec_coverage/__init__.py, slither/tools/kspec_coverage/__main__.py, slither/tools/kspec_coverage/analysis.py, slither/tools/kspec_coverage/kspec_coverage.py, tests/check-kspec/safeAdd/safeAdd.sol, tests/check-kspec/safeAdd/spec.md, tests/check-kspec/test_1.txt
Similar to https://github.com/crytic/slither/pull/360
The code was refactored to be simple, and the output was changed too
=> slither-check-kspec

slither/core/cfg/node.py, slither/core/declarations/contract.py, slither/printers/summary/contract.py, slither/solc_parsing/declarations/function.py
Contract summary: Show upgradeable information (fix #358) and if the contract is a most derived one
Contract: add is_upgradeable/is_upgradeable_proxy properties
Parsing: add inline assembly source code to the node
=> Improvements on the contract summary

README.md
- Shorten the list of detectors
- Add reference to Crytic
- Shorten and order printers
- Add tools description
- Add Slither academic paper
=> Refactor README:

slither/tools/flattening/flattening.py
=> slither-flat: stop early the exploration if the contract was seen

.github/workflows/ci.yml, README.md, scripts/travis_test_dapp.sh
Convert to actions! After this is merged we can do a follow-up PR to remove Travis.
=> GitHub Actions

slither/utils/output.py, tests/expected_json/old_solc.sol.json.solc-version.json, tests/expected_json/pragma.0.4.24.pragma.json, tests/expected_json/solc_version_incorrect.solc-version.json, tests/expected_json/solc_version_incorrect_05.ast.json.solc-version.json
Pragmas must have their source mapping for the ID generation, other it can lead to collisions
=> Fix id collision on pragma

slither/analyses/data_dependency/data_dependency.py
- Fix incorrect return type in get_dependencies
- Add get_dependencies_ssa, get_all_dependencies, get_all_dependencies_ssa
- Use python type on all the mentioned functions
=> Improve data dependencies API

slither/detectors/all_detectors.py, slither/detectors/statements/boolean_constant_equality.py, slither/detectors/statements/boolean_constant_misuse.py, slither/detectors/statements/divide_before_multiply.py, slither/detectors/statements/type_based_tautology.py, slither/slithir/variables/constant.py
- boolean-cst
- tautology
- boolean-equal
- divide-before-multiply
=> Open source 4 detectors

scripts/travis_test_dapp.sh, slither/detectors/variables/uninitialized_local_variables.py, slither/detectors/variables/uninitialized_storage_variables.py, tests/expected_json/uninitialized_local_variable.uninitialized-local.json, tests/expected_json/uninitialized_local_variable.uninitialized-local.txt, tests/expected_json/uninitialized_storage_pointer.uninitialized-storage.json, tests/expected_json/uninitialized_storage_pointer.uninitialized-storage.txt
Fix #398, a spelling mistake in uninitialized-local and uninitialized-storage
=> Fix spelling mistake 

slither/tools/flattening/__main__.py, slither/tools/flattening/flattening.py
Close #394
I did not add the conversion of public variables to internal, as constant functions should be filtered using the echidna printer
=> slither-flat: add --convert-private flag

slither/printers/guidance/echidna.py, slither/slithir/operations/high_level_call.py
=> Echidna printer: add support for state variable calls

slither/detectors/shadowing/builtin_symbols.py
Add detection of `fallback` and `receive` shadowing
=> Add fallback/receive as shadowed builtin

slither/visitors/slithir/expression_to_slithir.py
=> Add support for abi.decode on array 

slither/__main__.py, slither/analyses/write/are_variables_written.py, slither/core/declarations/contract.py, slither/core/expressions/call_expression.py, slither/core/expressions/new_contract.py, slither/printers/call/call_graph.py, slither/slithir/convert.py, slither/slithir/operations/new_contract.py, slither/slithir/tmp_operations/tmp_call.py, slither/slithir/tmp_operations/tmp_new_contract.py, slither/slithir/utils/ssa.py, slither/solc_parsing/declarations/contract.py, slither/solc_parsing/expressions/expression_parsing.py, slither/solc_parsing/slitherSolc.py, slither/tools/flattening/__main__.py, slither/tools/flattening/export/export.py, slither/tools/flattening/flattening.py, slither/tools/similarity/cache.py, slither/visitors/expression/expression.py, slither/visitors/slithir/expression_to_slithir.py
Merge latest `dev` into `dev-0.7`
=> Merge dev into dev-0.7

slither/solc_parsing/declarations/function.py
=> Fix incorrect ternary parsing 

slither/solc_parsing/declarations/function.py
=> Fix incorrect modifier parsing

slither/core/slither_core.py, slither/printers/functions/authorization.py, slither/printers/functions/cfg.py, slither/printers/inheritance/inheritance.py, slither/printers/inheritance/inheritance_graph.py, slither/printers/summary/contract.py, slither/printers/summary/data_depenency.py, slither/printers/summary/function.py, slither/printers/summary/human_summary.py, slither/printers/summary/slithir.py, slither/printers/summary/slithir_ssa.py, slither/solc_parsing/expressions/expression_parsing.py, slither/solc_parsing/slitherSolc.py, slither/solc_parsing/solidity_types/type_parsing.py
Note: this does not overcome the Truffle issue (https://github.com/trufflesuite/truffle/issues/3124)
=> Improve support of top-level structures and enums

slither/detectors/functions/suicidal.py
=> Detect suicidal external function

slither/solc_parsing/declarations/function.py
=> Prevent infinite loop on nested try/catch/if/then/else 

slither/tools/flattening/__main__.py, slither/tools/flattening/flattening.py
=> slither-flat: Add --pragma-solidity flag

slither/solc_parsing/declarations/function.py
=> Improve support for variable name reused

slither/printers/summary/function_ids.py
Fix #500 
Example:
```
$ slither 0xdac17f958d2ee523a2206206994597c13d831ec7 --print function-id
INFO:Printers:
SafeMath:
+------+----+
| Name | ID |
+------+----+
+------+----+
UpgradedStandardToken:
+-------------------------------------------------------+------------+
|                          Name                         |     ID     |
+-------------------------------------------------------+------------+
|         transferFrom(address,address,uint256)         | 0x23b872dd |
|                approve(address,uint256)               | 0x095ea7b3 |
|               allowance(address,address)              | 0xdd62ed3e |
|               allowance(address,address)              | 0xdd62ed3e |
|         transferFrom(address,address,uint256)         | 0x23b872dd |
| …
```
=> Add padding to function id printer

CONTRIBUTING.md, Dockerfile, README.md, plugin_example/README.md, scripts/fix_travis_relative_paths.sh, scripts/tests_generate_expected_json_4.sh, scripts/tests_generate_expected_json_5.sh, scripts/travis_test_4.sh, scripts/travis_test_5.sh, scripts/travis_test_cli.sh, scripts/travis_test_dapp.sh, scripts/travis_test_data_dependency.sh, scripts/travis_test_embark.sh, scripts/travis_test_erc.sh, scripts/travis_test_etherlime.sh, scripts/travis_test_etherscan.sh, scripts/travis_test_find_paths.sh, scripts/travis_test_kspec.sh, scripts/travis_test_printers.sh, scripts/travis_test_prop.sh, scripts/travis_test_simil.sh, scripts/travis_test_slither_config.sh, scripts/travis_test_truffle.sh, scripts/travis_test_upgradability.sh, slither/core/declarations/function.py, slither/core/expressions/call_expression.py, slither/detectors/abstract_detector.py, slither/tools/demo/README.md, slither/tools/erc_conformance/README.md, tests/check-kspec/safeAdd/spec.md
With the introduction of linting (see #549, #554) several warnings
and errors appeared. This PR fixes all of the Docker, shell and
Markdown ones and some of the Python ones.
=> Fix linting problems

slither/__main__.py, slither/core/slither_core.py, slither/slither.py, slither/solc_parsing/declarations/contract.py
Hidden flag that will help us to debug in case of partial analyses
=> Add --disallow-partial flag

slither/slithir/operations/type_conversion.py
Just add another case to the assertion. Fixes #557
=> Allow converting library to address

slither/solc_parsing/declarations/function.py, slither/visitors/slithir/expression_to_slithir.py
See https://github.com/crytic/slither/issues/529#issuecomment-662225727
=> Fix incorrect tuple index

slither/slithir/convert.py
Temporary solution until #566 is fixed
=> Add temporary support for abi.decode on complex type

slither/slithir/convert.py
=> Add type propgation for this.function usage

slither/slithir/operations/return_operation.py
=> IR: Add support for function pointer in RETURN operator

README.md, slither/tools/erc_conformance/__main__.py
=> "slither-erc" -> "slither-check-erc"

slither/slithir/convert.py, slither/slithir/operations/member.py
=> Improve the support of using_for for libraries functions 

.github/workflows/linter.yml
This will ease the review of the super-linter by having the results of pylint and black separated
=> Split super linter into three runs 

slither/core/cfg/node.py, slither/core/declarations/contract.py
code:
```
contract C {
uint a = 1;
uint b = 2;
uint c = 3;
uint d = 4;
}
```
before:
after:
=> fix state var cfg generation

slither/core/slither_core.py, slither/core/source_mapping/source_mapping.py, slither/solc_parsing/declarations/function.py, slither/solc_parsing/expressions/expression_parsing.py, slither/solc_parsing/slitherSolc.py, slither/solc_parsing/solidity_types/type_parsing.py, slither/solc_parsing/variables/variable_declaration.py
=> Fix some ValueErrors

slither/slithir/operations/binary.py
=> Allow function types as rvalues

CONTRIBUTING.md, slither/solc_parsing/slitherSolc.py, tests/test_ast_parsing.py
Related to https://github.com/crytic/slither/issues/681
=> Fix parsing tests

slither/tools/properties/properties/ercs/erc20/properties/transfer.py
This small PR will expand the ERC20 property descriptions to make them more precise.
=> Improved ERC20 property descriptions

slither/__main__.py
Hidden flag to measure performance
=> Add --perf flag

slither/detectors/functions/arbitrary_send.py, slither/detectors/functions/external_function.py, slither/detectors/operations/block_timestamp.py, slither/detectors/operations/low_level_calls.py, slither/detectors/statements/assembly.py, slither/detectors/statements/divide_before_multiply.py
Fix #486
As this changes the ID of some results, it might lead some triaged results to appear again
=> Fix deterministic output for multiple detectors

slither/detectors/statements/boolean_constant_equality.py, tests/detectors/boolean-constant-equality/boolean-constant-equality.sol, tests/detectors/boolean-constant-equality/boolean-constant-equality.sol.0.4.25.BooleanEquality.json, tests/detectors/boolean-equality/boolean-equality.sol, tests/test_detectors.py
Currently WIP, need to investigate problem with local dev environment setup which fails to generate the json artifact required to run the test.
=> Added tests for boolean equality detector

slither/core/solidity_types/user_defined_type.py
Fix #773
Require https://github.com/crytic/slither/pull/785 to pass the CI
=> Fix for top level user defined type

slither/solc_parsing/yul/parse_yul.py
=>  Add support for stop() in yul

slither/printers/summary/slithir.py, slither/slithir/convert.py
Fix #805
Additionally fix a minor bug in the slithir printer
Overall our types propagations rules are weak, and would benefit from more thorough review and testing
=> Fix signed integer type propagation

.github/workflows/ci.yml, examples/flat/a.sol, examples/flat/b.sol, scripts/ci_test_flat.sh
Follow up on https://github.com/crytic/slither/pull/791
=> Add slither-flat to the CI

slither/detectors/attributes/incorrect_solc.py
=> Update solc recommendations

slither/solc_parsing/expressions/expression_parsing.py
A bug was recently introduced (probably during the add of optimizations), which lead the IR to do incorrect lookup on shadowed function.
For example:
```solidity
contract A{
function _f() internal view returns(uint){
return 1;
}
function get() public view returns(uint){
return _f();
}
}
contract B is A{
function _f() internal view returns(uint){
return 2;
}
}
```
Lead to
```
Contract B
Function A._f() 
Expression: 1
IRs:
RETURN 1
Function A.get() (*)
Expression: _f()
IRs:
TMP_1(uint256) = INTERNAL_CALL, A._f()()
RETURN TMP_1
Function B._f() (*)
Expression: 2
IRs:
RETURN 2
```
Instead of 
```
Contract B
Function A._f() 
Expression: 1
IRs:
RETURN 1
Function A.get() (*)
Expression: _f()
IRs:
TMP_1(uint256) = INTERNAL_CALL, B._f()()
RETURN TMP_1
Function B._f() (*)
Expression: 2
IRs:
RETURN 2 …
```
=> Fix variable reference lookup

README.md, slither/core/declarations/contract.py, slither/detectors/all_detectors.py, slither/detectors/functions/dead_code.py, tests/detectors/dead-code/0.8.0/dead-code.sol, tests/detectors/dead-code/0.8.0/dead-code.sol.0.8.0.DeadCode.json, tests/test_detectors.py
This detector raises warnings if there are internal functions that are never used
=> Open source dead-code detector

slither/__main__.py, slither/utils/command_line.py
=> Add --checklist-limit flag

slither/core/declarations/contract.py, slither/tools/erc_conformance/__main__.py, slither/tools/erc_conformance/erc/erc1155.py, slither/utils/erc.py
This PR add the support to check for the correct implementation of [ERC1155](https://eips.ethereum.org/EIPS/eip-1155).
=> Add support of ERC1155 for slither-check-erc tool.

slither/detectors/compiler_bugs/public_mapping_nested.py, slither/slithir/convert.py, slither/solc_parsing/expressions/expression_parsing.py
- Add support for event called through libraries
- Improve public mapping compiler bug detector
- Improve parsing of unkown type for recent solc versions
=> Multiple small fixes

slither/detectors/variables/unused_state_variables.py
Updated WIKI reference link for unused-state-variable
=> Updated WIKI reference link

slither/detectors/erc/unindexed_event_parameters.py
Partially closes #970 (also needs to change Github's wiki)
=> Fix typo in doc

slither/detectors/all_detectors.py, slither/detectors/statements/delegatecall_in_loop.py, tests/detectors/delegatecall-loop/0.4.25/delegatecall_loop.sol, tests/detectors/delegatecall-loop/0.4.25/delegatecall_loop.sol.0.4.25.DelegatecallInLoop.json, tests/detectors/delegatecall-loop/0.5.16/delegatecall_loop.sol, tests/detectors/delegatecall-loop/0.5.16/delegatecall_loop.sol.0.5.16.DelegatecallInLoop.json, tests/detectors/delegatecall-loop/0.6.11/delegatecall_loop.sol, tests/detectors/delegatecall-loop/0.6.11/delegatecall_loop.sol.0.6.11.DelegatecallInLoop.json, tests/detectors/delegatecall-loop/0.7.6/delegatecall_loop.sol, tests/detectors/delegatecall-loop/0.7.6/delegatecall_loop.sol.0.7.6.DelegatecallInLoop.json, tests/detectors/delegatecall-loop/0.8.0/delegatecall_loop.sol, tests/detectors/delegatecall-loop/0.8.0/delegatecall_loop.sol.0.8.0.DelegatecallInLoop.json, tests/test_detectors.py
This PR add a new detector to check for the usage of delegatecall inside a loop in a payable function
=> Add detector delegatecall inside a loop

slither/detectors/all_detectors.py, slither/detectors/statements/msg_value_in_loop.py, tests/detectors/msg-value-loop/0.4.25/msg_value_loop.sol, tests/detectors/msg-value-loop/0.4.25/msg_value_loop.sol.0.4.25.MsgValueInLoop.json, tests/detectors/msg-value-loop/0.5.16/msg_value_loop.sol, tests/detectors/msg-value-loop/0.5.16/msg_value_loop.sol.0.5.16.MsgValueInLoop.json, tests/detectors/msg-value-loop/0.6.11/msg_value_loop.sol, tests/detectors/msg-value-loop/0.6.11/msg_value_loop.sol.0.6.11.MsgValueInLoop.json, tests/detectors/msg-value-loop/0.7.6/msg_value_loop.sol, tests/detectors/msg-value-loop/0.7.6/msg_value_loop.sol.0.7.6.MsgValueInLoop.json, tests/detectors/msg-value-loop/0.8.0/msg_value_loop.sol, tests/detectors/msg-value-loop/0.8.0/msg_value_loop.sol.0.8.0.MsgValueInLoop.json, tests/test_detectors.py
This PR add a new detector to check for the usage of msg.value inside a loop
=> Add detector use of msg.value inside a loop

CONTRIBUTING.md
Add information on how to synchronize with crytic-compile
=> Update contributing.md with crytic-compile info

.github/workflows/ci.yml, slither/detectors/attributes/incorrect_solc.py, tests/detectors/solc-version/0.5.14/static.sol.0.5.14.IncorrectSolc.json
Until #993 is solved
(the PR contains https://github.com/crytic/slither/pull/999)
=> Disable slither-prop from CI 

slither/detectors/attributes/incorrect_solc.py, tests/detectors/solc-version/0.5.14/static.sol.0.5.14.IncorrectSolc.json
- Recommend Solidity 0.8.4-0.8.7
- Better output if a buggy version is used
=> Update solc version recommendations

slither/printers/summary/modifier_calls.py
--print modifiers --json modifiers.json no json output file bug
=> fix  modifiers  no json output file bug

slither/printers/guidance/echidna.py
required by https://github.com/crytic/echidna/issues/595
=> In Echidna printer output list of solc versions used

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
=> add bug and feature request templates

slither/detectors/functions/dead_code.py, tests/detectors/dead-code/0.8.0/dead-code.sol
Fixes - https://github.com/crytic/slither/issues/929
=> fix issue-929, FP in dead-code detector

slither/__main__.py, slither/utils/command_line.py
Fix https://github.com/crytic/slither/issues/1052
=> add check for default config file

slither/slithir/operations/phi.py
=> Fix missing 'f' at beginning of f-string

slither/detectors/source/rtlo.py, tests/detectors/rtlo/0.8.0/unicode_direction_override.sol, tests/detectors/rtlo/0.8.0/unicode_direction_override.sol.0.8.0.RightToLeftOverride.json, tests/test_detectors.py
This PR corrects a bug in the RTLO detector causing slither to hang forever. Closes #1081
=> Fix infinite loop in RTLO detector

.github/workflows/IR.yml, .github/workflows/ci.yml, .github/workflows/detectors.yml, .github/workflows/features.yml, .github/workflows/parser.yml, setup.py
pytest 7.1.x dropped the support for python 3.6, and breaks our CI
=> Use pytest 7.0.1

slither/detectors/statements/too_many_digits.py, tests/detectors/too-many-digits/0.4.25/too_many_digits.sol, tests/detectors/too-many-digits/0.4.25/too_many_digits.sol.0.4.25.TooManyDigits.json, tests/detectors/too-many-digits/0.5.16/too_many_digits.sol, tests/detectors/too-many-digits/0.5.16/too_many_digits.sol.0.5.16.TooManyDigits.json, tests/detectors/too-many-digits/0.6.11/too_many_digits.sol, tests/detectors/too-many-digits/0.6.11/too_many_digits.sol.0.6.11.TooManyDigits.json, tests/detectors/too-many-digits/0.7.6/too_many_digits.sol, tests/detectors/too-many-digits/0.7.6/too_many_digits.sol.0.7.6.TooManyDigits.json
Fixes https://github.com/crytic/slither/issues/928
=> Ignore checksummed address

.github/workflows/pip-audit.yml
Replaces the manual use here with our official GitHub Action.
=> pip-audit: Use our official action

slither/__main__.py, slither/core/declarations/contract.py, slither/utils/erc.py
=> Support of ERC1363, ERC4524 for slither-check-erc

CONTRIBUTING.md, README.md
Started a brief FAQ. Going to think of others and add those (open to suggestions). 
I also updated the testing section so it's more clear how to update existing detectors. I'd appreciate feedback of the "project layout" section since there's likely better descriptions.
=> add FAQ and useful info to contribution guidelines

examples/scripts/taint_mapping.py, slither/core/declarations/function.py, slither/detectors/statements/calls_in_loop.py, slither/detectors/statements/costly_operations_in_loop.py, slither/detectors/statements/delegatecall_in_loop.py, slither/detectors/statements/msg_value_in_loop.py, slither/detectors/variables/uninitialized_local_variables.py, slither/detectors/variables/uninitialized_storage_variables.py
=> Make entry_point return an Optional[Node] and update the detectors

setup.py
`dependency_links` has been deprecated
=> Fix deps install

slither/detectors/statements/unprotected_upgradeable.py
so syntax highlighting applies in github wiki
=> updated formatting of Unprotected upgradeable contract 

slither/slithir/convert.py
Fixes https://github.com/crytic/slither/issues/1407
=> Fix detection of library events

slither/detectors/variables/possible_const_state_variables.py
https://github.com/crytic/slither/pull/1375 + a couple of code quality / types improvements
=> Constants detector: Also detect Contract types

slither/detectors/erc/erc20/arbitrary_send_erc20_no_permit.py, slither/detectors/erc/erc20/arbitrary_send_erc20_permit.py
This PR fixes two broken links for the WIKI concerning `arbitrary-send-erc20`.
=> chore: fix broken links

slither/printers/functions/authorization.py, slither/printers/summary/data_depenency.py, slither/printers/summary/function.py, slither/printers/summary/modifier_calls.py, slither/printers/summary/require_calls.py
Outputs of several printers sorted so that they print consistent results.
Fixes #1374 
I have tried to find all places where the outputs might not possibly be deterministic, but if you find another one, please let me know.
=> Printer outputs sorted

.github/workflows/pip-audit.yml
Tentative to fix https://github.com/crytic/slither/issues/1538
=> Use latest setuptools in CI

.github/workflows/pip-audit.yml, setup.py, slither/core/scope/scope.py, slither/detectors/attributes/constant_pragma.py, slither/printers/summary/evm.py, slither/slithir/convert.py, tests/source_unit/foundry.toml, tests/source_unit/script/Counter.s.sol, tests/source_unit/src/Counter.sol, tests/source_unit/src/Counter2.sol, tests/source_unit/test/Counter.t.sol, tests/test_source_unit.py
Update for the changes made by https://github.com/crytic/crytic-compile/pull/316
=> Update to the latest crytic-compile source unit API

slither/core/expressions/literal.py, slither/printers/guidance/echidna.py, slither/visitors/expression/constants_folding.py, tests/constant_folding_binop.sol, tests/test_constant_folding.py
close https://github.com/crytic/slither/issues/1427
=> fold binary expressions with constant operands for fuzzing guidance

slither/detectors/variables/unchanged_state_variables.py, tests/detectors/immutable-states/0.4.25/immut_state_variables.sol, tests/detectors/immutable-states/0.5.16/immut_state_variables.sol, tests/detectors/immutable-states/0.6.11/immut_state_variables.sol, tests/detectors/immutable-states/0.7.6/immut_state_variables.sol, tests/detectors/immutable-states/0.8.0/immut_state_variables.sol, tests/detectors/immutable-states/0.8.0/immut_state_variables.sol.0.8.0.CouldBeImmutable.json
close https://github.com/crytic/slither/issues/1595
=> do not recommend to make string immutable 

.github/workflows/IR.yml, .github/workflows/black.yml, .github/workflows/ci.yml, .github/workflows/detectors.yml, .github/workflows/docker.yml, .github/workflows/doctor.yml, .github/workflows/features.yml, .github/workflows/linter.yml, .github/workflows/parser.yml, .github/workflows/pip-audit.yml, .github/workflows/pylint.yml, .github/workflows/read_storage.yml
See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
=> Cancel action on new commits

README.md
- update references to compilation frameworks
- add link to documentation site
- move installation instructions front and center
- explain usage for projects with dependencies
=> update and reorganize README

.github/workflows/ci.yml
closes https://github.com/crytic/slither/issues/1700
ref https://github.com/cachix/cachix-action/issues/144
=> upgrade nix installation to fix CI installation

slither/detectors/functions/cyclomatic_complexity.py
Quote (") sign removed from the end of detector's WIKI URL.
=> WIKI URL fixed

scripts/ci_test_etherscan.sh, setup.py
Use cc@master
Remove rinkeby test (etherscan does not support rinkeby anymore)
=> Sync cc@master

slither/__main__.py
close https://github.com/crytic/slither/issues/1144
=> update filter-paths help

slither/core/compilation_unit.py, slither/core/declarations/contract.py, slither/printers/functions/authorization.py, slither/printers/functions/cfg.py, slither/printers/inheritance/inheritance.py, slither/printers/inheritance/inheritance_graph.py, slither/printers/summary/contract.py, slither/printers/summary/data_depenency.py, slither/printers/summary/function.py, slither/printers/summary/human_summary.py, slither/printers/summary/slithir.py, slither/printers/summary/slithir_ssa.py, slither/solc_parsing/slither_compilation_unit_solc.py
Closes https://github.com/crytic/slither/issues/1767
=> remove is_top_level dead code

slither/utils/expression_manipulations.py, tests/unit/slithir/test_data/ternary_expressions.sol
closes https://github.com/crytic/slither/issues/1813
=> support new bytes expr in ternary

.github/workflows/black.yml, .github/workflows/linter.yml, .github/workflows/pylint.yml
https://github.com/super-linter/super-linter/issues/4150
=> update super-linter org

slither/slithir/convert.py
=> Fix pop IR

slither/detectors/variables/unchanged_state_variables.py, slither/detectors/variables/unused_state_variables.py
Closes https://github.com/crytic/slither/issues/1884, closes https://github.com/crytic/slither/issues/1883
=> do not recommend changing mutability for abstract contracts

slither/detectors/statements/msg_value_in_loop.py
=> docs: update recommendation for msg.value-inside-a-loop

README.md
PyPI needs a link to properly render the logo
xref https://github.com/pypi/warehouse/issues/5246
=> fix logo on pypi

slither/core/declarations/__init__.py, slither/core/declarations/custom_error_contract.py, slither/core/declarations/custom_error_top_level.py, slither/utils/output.py
=> Add CustomError as printable output

slither/__main__.py
=> Fix a typo in the help text

slither/slithir/convert.py
=> Fix abi.decode tuple result with udt

slither/printers/guidance/echidna.py
=> Improve constants extraction of ReferenceVariable

slither/printers/guidance/echidna.py
Revert https://github.com/crytic/slither/pull/2105 until format is supported by echidna.
=> revert https://github.com/crytic/slither/pull/2105

slither/solc_parsing/slither_compilation_unit_solc.py
fixed issue #2304 with the way suggested in the issue
=> fixed immediate inheritance

tests/unit/slithir/test_implicit_returns.py
Implement pytest parameterize on `test_implicit_returns.py` for issue #2350
=> Implement pytest parameterize on test_implicit_returns (#2350)

slither/detectors/functions/modifier.py, tests/e2e/detectors/snapshots/detectors__detector_ModifierDefaultDetection_0_4_25_modifier_default_sol__0.txt, tests/e2e/detectors/snapshots/detectors__detector_ModifierDefaultDetection_0_5_16_modifier_default_sol__0.txt, tests/e2e/detectors/snapshots/detectors__detector_ModifierDefaultDetection_0_6_11_modifier_default_sol__0.txt, tests/e2e/detectors/snapshots/detectors__detector_ModifierDefaultDetection_0_7_6_modifier_default_sol__0.txt
closes https://github.com/crytic/slither/issues/2169
=> fix: add newline to incorrect-modifier output

slither/core/declarations/function.py
Add recursive functions to get all the variables read and written in a function
=> Add all variables read/written

setup.py
https://github.com/ethereum/web3.py/issues/3346
=> ci: require web3 with <5 eth_typing deps

setup.py
fixes https://github.com/crytic/slither/issues/2539
=> add upper bound

slither/detectors/all_detectors.py, tests/e2e/detectors/test_detectors.py
while https://github.com/crytic/slither/issues/2477 is not fixed, we will disable this detector
=> disable unused import

slither/printers/call/call_graph.py
Build on top of https://github.com/crytic/slither/pull/2603 + run black
=> PR 2603 improvements

docs/src/detectors/Detector-Documentation.md, scripts/ci_test_data_dependency.sh, slither/detectors/statements/pyth_unchecked.py, slither/detectors/statements/write_after_write.py
=> chore: fix some typos in comment
